### ISSUE TITLE
alternative AM key

### ISSUE THREAD

**Issue by michaelBelsanti** [abenz1267/walker#10]
I think it would be great to be able to use an alternative AM key, whether that be multiple options or just the option to use alt instead of control.

My muscle memory currently has me pressing control + A to select my search text and replace it, which is causing me to open apps by accident.

**Comment by michaelBelsanti** [comment]
If you're interested in adding this, I wrote a patch that adds an `am_key` config option that lets you choose control or alt, defaulting to control.

**Comment by abenz1267** [comment]
feel free to open up a PR!

**Comment by abenz1267** [comment]
closed by #11
