### ISSUE TITLE
wrong  HM name

### ISSUE THREAD

**Issue by Ciflire** [abenz1267/walker#100]
hi as of 8b57df57f4595c8d14d4f14dc0b951bce5295cab the `inputs.walker.homeManagerModule.walker` doesn't exist
`inputs.walker.homeManagerModules.default` should be used instead
i'm refering here to the documentation that is not up to date
I will maybe make a PR if i have time

**Comment by abenz1267** [comment]
@diniamo ?

**Comment by abenz1267** [comment]
fixed
