### ISSUE TITLE
home manager module not working

### ISSUE THREAD

**Issue by sudanbhurtel** [abenz1267/walker#104]
**Describe the bug**
The default config file to look for when using home manager module is set as "default = importJSON ../config/config.default.json;" , but the actual default config is in "../internal/config/config.default.json". So it needs to be changed.

**Version**
v0.6.9

**To Reproduce**
Try using home manager module with the default config.

**Desktop**
 - OS Nix
 - DE Hyprland

**Comment by abenz1267** [comment]
should be done. pls verify.

**Comment by sudanbhurtel** [comment]
> should be done. pls verify.
Thank you for the quick fix. And I hope to see this project flourish because this program is very good. A true successor to “anyrun” with so much improvement. Thank you again!!!
