### ISSUE TITLE
Cachix: build  and push on every commit

### ISSUE THREAD

**Issue by Ciflire** [abenz1267/walker#105]
**Is your feature request related to a problem? Please describe.**
when using it through with the current config i regularly need to rebuild which is time consuming

**Describe the solution you'd like**
there are many solutions to that problem
- first one is creating a branch for "unstable" or git version that get the latest commits every now and then and build the package people would use that branch as a flake input and always have the cachix there for them
- second option is to use flakehub just heard of it but i don't know what it is

**Additional context**
This is a nix specific issue and would make the cachix usefull 100% of the time
This could cause a problem where latest build are not tested by nix users and you could lose some feedbacks on latest commits

**Have you checked the wiki?**
Yes?

**Comment by abenz1267** [comment]
What i've done:

- added second cachix cache
- adjusted readme so the flake uses the 2nd cache

There's 2 caches now:
1. walker: build on tag
2. walker-git: build on push

Should do it?

**Comment by Ciflire** [comment]
it should but i really believe the build on tag will not be used
i think the cache is only used for the flake input meaning that the version it is pointing to is either random or pointing to a specific version but would imply the flake would've to be modified each time the user wants to update I don't believe this how it is used

**Comment by abenz1267** [comment]
I'll just keep both. doesn't hurt.

can be closed?

**Comment by Ciflire** [comment]
just redondant
just tested all good for me
