### ISSUE TITLE
Startup time slower even though running as gapplication service

### ISSUE THREAD

**Issue by AlxTray** [abenz1267/walker#106]
**Describe the bug**
I have a shell script that launches "walker --gapplication-service" and walker normally (to have it open on boot). But even though it should be running as a service, subsequent walker calls seem to not use the service and are slower to launch then when I was previously using the runAsService option to create the systemd service.

**Version**
Master

**Minimal Config**
Config is currently default, and theme is same as Kanagawa theme (though defined in Nix home manager)

**To Reproduce**
The script I have in my exec-once of Hyprland is just:

walker --gappliaction-service
sleep 0.5
walker

**Expected behavior**
I would think this would launch the walker service, then launch walker using the service, and then continue using the service for any following walker calls.

**Screenshots**
N/A

**Desktop**
 - OS Nix
 - DE Hyprland

**Additional context**
I have the option runAsService disabled btw, but this is equivalent to --gapplication-service afaik

**Comment by abenz1267** [comment]
You'd need to provide a full script.

You can do `walker --gapplication-service -b` and `walker -b` to see if the service is being called. The service should log (after opening second time) something along the lines of `Visible (re-open)`.

For Hyprland I personally just do `exec-once=walker --gapplication-service` in my Hyprland config.

**Comment by AlxTray** [comment]
When I run walker -b with the script running walker -gapplication-service I get this:

walker -b
Startup:  1723312375924064418
start run:  1723312375924180311
start handle cmd:  1723312375948708075
run activate:  1723312375948723689
Calc disabled: currently 'qalc' only.
INFO Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkWaylandToplevel': Failed to create EGL display
 priority=5 code_file=../gsk/gskrenderer.c code_line=753 code_func=gsk_renderer_new_for_surface glib_domain=Gsk
INFO Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkWaylandToplevel': Failed to create EGL display
 priority=5 code_file=../gsk/gskrenderer.c code_line=753 code_func=gsk_renderer_new_for_surface glib_domain=Gsk
INFO Failed to realize renderer of type 'GskVulkanRenderer' for surface 'GdkWaylandToplevel': Could not create a Vulkan instance: The requested version of Vulkan is not supported by the driver or is otherwise incompatible for implementation-specific reasons. (VK_ERROR_INCOMPATIBLE_DRIVER)
 priority=5 code_file=../gsk/gskrenderer.c code_line=753 code_func=gsk_renderer_new_for_surface glib_domain=Gsk
Visible (first ui) 1723312376353565998

and then running walker -gapplication-service -b and then running walker -b all of the debug mesagges are displayed from the --gapplication-call. So I would assume the service is not running initially from this.

This is the script:

{ pkgs, ... }:

pkgs.writeShellScriptBin "walkerLaunch" ''
  walker --gapplication-launch
  walker
''

**Comment by abenz1267** [comment]
That scripts looks cursed. i literally dunno what this is even supposed to do. why do you run walker after starting the service?

Log messages being shown in the server instance, means the server instance is working.

**Comment by AlxTray** [comment]
Yeah I probably am doing something wrong on the script side, but it is just meant to start the service and then launch walker straight after so it appears straight away on boot

**Comment by AlxTray** [comment]
It’s also in Nix so that will just equate to a script file that is just what is in the “”

**Comment by abenz1267** [comment]
I mean, sure... the script executes things.... but if it closes, it also closes the service.

**Comment by AlxTray** [comment]
Ahh, yes of course it does. I was doing this because as far as I know the order of the exec-once calls are arbitrary so I can’t do:
exec-once = walker —gapplication-service
exec-once = walker

As I was running into a similar problem here, though this might be due to a different reason I’m not sure

**Comment by abenz1267** [comment]
I mean.. if you only want it to be shown when opening Hyprland... you'd just do `exec-once=walker -n` i guess? + ofc launching the service anyways for other usage.

**Comment by AlxTray** [comment]
Yep, that makes more sense. Thanks. I was originally starting on Hyprland launch as the first launch when the service is running in the background is like a normal launch, but I would assume that is by design.
