### ISSUE TITLE
Walker doesn't auto focus on load

### ISSUE THREAD

**Issue by 0x006E** [abenz1267/walker#107]
**Describe the bug**
I am not sure from which revision this happen to occur, but now walker doesn't autofocus when opened. I need to either click the walker window to focus on it to launch anything. This did not occur in versions before using the new default theme?. 

**Version**
Current, walker --version not returning anything, just hanging

**Minimal Config**
```
  programs.walker = {
    enable = true;
    runAsService = true;
  };
```

**To Reproduce**
1. Run walker,
2. Do anything on keyboard to interact with walker
3. Click on the window, mouse hover doesn't seem to focus. 
4. Now you can interact with walker using keyboard 

**Expected behavior**
1. Autofocus on search input on spawn. This used to work before the theme change. This also maybe a issue on my config too. I'm not sure.

**Screenshots**

https://github.com/user-attachments/assets/adf3acef-6270-44d1-a1a5-9734898949f4

**Desktop**
 - OS NixOS
 - DE Niri

**Comment by abenz1267** [comment]
It should grab focus... there was a `force_keyboard_focus` setting before which you prob. had set to true? That setting got removed, because it broken the window switcher.

I could add that back if you want....

**Comment by 0x006E** [comment]
I haven't changed anything, I had used the default config now and then. So I am not sure what broke the focus. I haven't also checked in any other WMs so this may also be niri problem too.

Is there anyway I can some debug info or anything like that? Or any relevant info?

Is there any temporary fix, that would be great too

**Comment by abenz1267** [comment]
I've actually just installed Niri to try and debug this, but i can't get the Walker window to get focus at all. Not even when clicking.

There's also not much magic going on here...just a simple GTK call to focus the input. So nothing really to debug.

Maybe open an issue with Niri? I'll investigate further a bit... but this seems broken.

**Comment by 0x006E** [comment]
So I've rollback the walker flake to revision b21d226d9ec6e379b13b633515af301d223cedcd and it autofocuses correctly. I'll add an issue on the niri repo too. 

https://github.com/user-attachments/assets/e1311ea3-19cc-4b9b-967b-a932b58819c6

**Comment by abenz1267** [comment]
I've tracked down the issue down to commit c69820dc, the one where i removed the `force_keyboard_focus` option.

But this indeed doesn't help anything, as Walker should still get focus.

**Comment by abenz1267** [comment]
I've just re-added the "force_keyboard_focus" option which defaults to true. This should fix your problem. Window focusing works on niri and sway as well, even if it's forcing keyboard focus.

**Comment by 0x006E** [comment]
Maybe this is related? https://github.com/YaLTeR/niri/wiki/Layer%E2%80%90Shell-Components

**Comment by YaLTeR** [comment]
If I'm not mistaken, currently on niri on-demand layers can get focus either on click or on focus-follows-mouse hover. I'm not sure they get focus when they first appear.

**Comment by 0x006E** [comment]
I have enabled focus-follows-mouse and put the mouse on where the window should appear and walker still doesn't get any keyboard focus, but pointer focus is there. But I do see that, focus-follows-mouse doesn't seem to work walker is spawned.

**Comment by YaLTeR** [comment]
focus-follows-mouse (intentionally) only works when you move the mouse across focusable surfaces, not when something changes underneath the mouse.

**Comment by cramt** [comment]
i've been experiencing the same problem on sway, though for me its never graped focus since i installed it back in 0.7.0

**Comment by abenz1267** [comment]
"force_keyboard_focus" has already been re-added and defaults to true. I just tested and it grabs focus correctly in sway and niri.
