### ISSUE TITLE
Favoring a module over others (config option)

### ISSUE THREAD

**Issue by Evangelospro** [abenz1267/walker#108]
**Is your feature request related to a problem? Please describe.**
I like to run walker with all modules enabled, but would like some  modules to take precedence over some others. So that I still have all the modules available but it is quite difficult to quickly launch apps because some times the current windows come up (from the windows module) even though I usually want to create a new instance of that application.

**Describe the solution you'd like**
It would be nice if there was some kind of weighting system, that would be configured per module, in order for that module to be prefered "generally"

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/user-attachments/assets/e07a9847-2b1f-498d-8f00-817d308c0003)

**Have you checked the wiki?**
Yes

**Comment by abenz1267** [comment]
Modules have a new `weight` option. All modules default to `5`. Higher = more priority.

Try that.

**Comment by Evangelospro** [comment]
Seems to work thanks!
