### ISSUE TITLE
Switcher_only modules are only omitted from the list if something is typed into search

### ISSUE THREAD

**Issue by henriqpsantos** [abenz1267/walker#110]
**Describe the bug**
Switcher-only modules defined by config (file in `~/.config/walker/_config.yaml`, running `walker -c ~/.config/walker/_config.yaml`

```
builtins:
    applications:
        switcher_only: true
```

only get hidden after the user types a key.

Aditionally, I can't seem to disable any modules through the config, i.e.:

```
disabled:
    - runner
    - emojis
    - dmenu
    - windows
    - ssh
    - websearch
    - finder
    - hyprland
    - applications
    - clipboard
```

Still shows all modules.

**Version**
0.7.3 (latest)

**Minimal Config**
See above.

**To Reproduce**
Run `walker -c ~/.config/walker/_config.yaml` as described above. Applications still show up in the default screen. Only after typing a character does the set of applications get hidden as expected.
Disabled modules should not show up in the search window.

**Expected behavior**
switcher_only config option to work as expected.

**Desktop**
Fedora Linux 40
DE: Hyprland

**Comment by abenz1267** [comment]
Modules not being disabled has already been fixed in git.

Right now "show_initials" means = show applications = doesnt matter if switcher only or not.

That behaviour is subject to change... not sure yet.
