### ISSUE TITLE
shortcut bars to moules or plugins 

### ISSUE THREAD

**Issue by HK-Sepuri** [abenz1267/walker#113]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I found out that you can add pluins in walker and can add power menue which is great but i am also using wlogout so i want to remove it and use walker only but its 4 step process , open walker use '/' for switcher n type power menu and then shutdown/logout/hyprlock etc , it would be better if steps are less

**Describe the solution you'd like**
wouldnt it be better if can add shortcuts to it , like a separate bar or panels to walker app , either of left/right/bottom where power symbols are or other shortcuts like calculator , other apps etc , most people add these in their bars but an option to add in walker would e better not to stuff everything in bars only 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.i can make up keybinding of everything and use conky or cheet sheet to remind me all keybinding if i ever forget but why make it too complicated 

**Additional context**

**Have you checked the wiki?**
Yes?

**Comment by abenz1267** [comment]
![image](https://github.com/user-attachments/assets/7983448f-0d4c-41f1-abba-f24dea5f302d)

I've just added this.

**Comment by HK-Sepuri** [comment]
Yay!
