### ISSUE TITLE
Don't trim white spaces for clipboard

### ISSUE THREAD

**Issue by noamsto** [abenz1267/walker#117]
**Describe the bug**
Don't trim white spaces for clipboard. It leads to unexpected behavior in some apps. For example vim/neovim copy line (yy) should preserve the new line prefix and suffix. 
(This eligible only if vim/neovim clipboard are synced with system clipboard)

**Version**
0.7.6

**To Reproduce**
Setup vim/neovim clipbaord sync with system clipboard, press 'yy' and 'p' (after 500 ms :D).

**Expected behavior**
Copied text should be untouched, including white-spaces.

**Desktop**
 - Nixos
 - Hyprland

**Additional context**
I can open a PR with a fix...

**Comment by abenz1267** [comment]
Yes, I agree, although I personally would make it a config option for the clipboard module. In the end your editors formatter should just.... "fix" it anyways?

The clipboard module needs a slight rework to avoid the 500ms clipboard fetching anyways.

**Comment by noamsto** [comment]
I would suggest that the default behavior is to not do any manipulation on copied text unless user specifically set "trim-spaces" option.
If I'm in the middle of editing a file and I want to preserve new-lines or spaces (indentation), I can't copy paste correctly like this.
User can just select and copy text without new lines and spaces which is usually default behavior  when you double click on a word/sentence with the mo explicitly select white-spaces, he probably wants them to be copied :)
use. But if a user explicitly select white-spaces, he probably wants them to be copied :)

I'm quite noob at go,
But maybe utilizing the command 'wl-paste --watcher' can improve the fetching.
