### ISSUE TITLE
Go build -x "no Go files in ..."

### ISSUE THREAD

**Issue by JarzaClay** [abenz1267/walker#119]
**Describe the bug**
When compiling from source, I get the error "no Go files in /var/tmp/portage/gui-apps/walker-0.7.6//work" I am making a gentoo ebuild, so compiling from source is required. The go files are in sub-directories, but Go doesn't look there?

**Version**
Walker version.
0.7.6

**Minimal Config**
Provide a minimal config to reproduce the bug.
/var/db/repos/local/gui-apps/walker/walker-0.7.6.ebuild
```# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

DESCRIPTION="Walker - A simple application launcher for Wayland"
HOMEPAGE="https://github.com/abenz1267/walker"
SRC_URI="https://github.com/abenz1267/walker/archive/refs/tags/v0.7.6.tar.gz -> walker.tar.gz"
LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

# Dependencies
RDEPEND="
    dev-lang/go
    gui-libs/gtk
    gui-libs/gtk4-layer-shell
    dev-libs/gobject-introspection
"
DEPEND="${RDEPEND}"

src_unpack() {
    # Extract the source tarball
    unpack "walker.tar.gz"
    cd "/var/tmp/portage/gui-apps/walker-0.7.6/"
}

src_compile() {
    # Build the application using Go
    go build -x || die "Build failed"
}

src_install() {
    # Install the binary
    # Install into the appropriate directory
    install -D -m 0755 walker "${D}/usr/bin/walker"
}
```

**To Reproduce**
Steps to reproduce the behavior.
Run this ebuild

**Expected behavior**
It compiles

**Screenshots**

**Desktop**
 - OS Gentoo
 - DE Hyprland

**Additional context**

**Comment by abenz1267** [comment]
fixed.
