### ISSUE TITLE
results flicker when typing fast

### ISSUE THREAD

**Issue by zspher** [abenz1267/walker#120]
**Describe the bug**
the results list flickers when typing too fast

**Version**
0.7.6

**Minimal Config**
Provide a minimal config to reproduce the bug.

```json
{
  "activation_mode": {
    "labels": "jkl;asdf",
    "use_alt": true
  },
  "as_window": false,
  "theme": "catppuccin"
}
```

**To Reproduce**
1. run `walker`
2. type fast

**Expected behavior**
results list should not flicker

**Screenshots**

https://github.com/user-attachments/assets/02d27f4a-f18e-47d2-a822-4be747797b7a

**Desktop**

- OS: `Linux 6.6.47, NixOS, 24.11 (Vicuna), 24.11.20240821.c374d94`
- DE: `Hyprland v0.42.0`

**Additional context**

**Comment by abenz1267** [comment]
If you want to avoid flickering you have different options:
- set search.delay in your config, see https://docs.gtk.org/gtk4/property.SearchEntry.search-delay.html
- put a background color around the whole box

Like... it's not a bug. You type => you get new search entries.

**Comment by zspher** [comment]
i'v added the delay to search but the flicker still happens 

flicker at search.delay = 1s


https://github.com/user-attachments/assets/cb7119bb-0215-4ffe-952d-8b94a251c1e9

contrasted to anyrun where only the individual search items sort of flicker, not the whole box


https://github.com/user-attachments/assets/861432dd-18a1-48c5-af6e-1774cf0cdc09

**Comment by abenz1267** [comment]
Ah, i see now. The videos weren't playing for me.

Should be fixed.. will create a release.
