### ISSUE TITLE
User desktop entries not overriding system entries when NoDisplay is true

### ISSUE THREAD

**Issue by PZeide** [abenz1267/walker#123]
**Describe the bug**
When I try to override a system desktop entry using a custom user entry (in `~/.local/share/applications`) everything works flawlessly.
However, when I want to add the property `NoDisplay` to that custom entry, it is ignored and revert back to the system one.
This behavior is not compliant of the FDO Desktop Entry spec (Cf. [spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/file-naming.html)).

**Version**
0.7.7

**Minimal Config**
N/A

**To Reproduce**
- Create a copy of a system-wide entry into the user desktop entry directory (`~/.local/share/applications`).
- Add `NoDisplay=true`

**Expected behavior**
Since the user desktop entry should override the system-wide one, the corresponding entry should be hidden from the menu.

**Screenshots**
N/A

**Desktop**
 - OS (Arch, Nix etc) Arch
 - DE (Plasma, Hyprland etc. ) Hyprland

**Comment by abenz1267** [comment]
This can be closed with the merging of your PR, right?
