### ISSUE TITLE
Failed to create EGL display

### ISSUE THREAD

**Issue by Ciflire** [abenz1267/walker#125]
**Describe the bug**
while running on dgpu everything works as expected, but when dgpu is dsabled (in a prime setup), walker takes almost 10 second to open a window

**Version**
Latest git (or almost)

**Minimal Config**
Default config without system

**To Reproduce**
 open from terminal or using hyprland shortcut

**Expected behavior**
opening in a second or so

**Desktop**
 - NixOS
 - Hyprland

**Additional context**
I have two gpus, on dedicated (nvidia) and one integrated
If you need any environment i will give it to you, i'd like not to spam the issue with irrelevant env var (especially the nix ones)

this is the output i get from a terminal, with benchmark
```
~ took 45s 
    walker -b
Startup:  1726227529471
start run:  1726227529471
start handle cmd:  1726227529498
run activate:  1726227529498
Calc disabled: currently 'qalc' only.
INFO Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkWaylandToplevel': Failed to create EGL display
 priority=5 code_file=../gsk/gskrenderer.c code_line=753 code_func=gsk_renderer_new_for_surface glib_domain=Gsk
INFO Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkWaylandToplevel': Failed to create EGL display
 priority=5 code_file=../gsk/gskrenderer.c code_line=753 code_func=gsk_renderer_new_for_surface glib_domain=Gsk
ERROR Vulkan: Loader Message: setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config priority=4 code_file=../gdk/gdkvulkancontext.c code_line=1575 code_func=gdk_vulkan_debug_report glib_domain=Gdk
ERROR Vulkan: Loader Message: setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config priority=4 code_file=../gdk/gdkvulkancontext.c code_line=1575 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Failed to realize renderer of type 'GskVulkanRenderer' for surface 'GdkWaylandToplevel': No Vulkan devices available.
 priority=5 code_file=../gsk/gskrenderer.c code_line=753 code_func=gsk_renderer_new_for_surface glib_domain=Gsk
Visible (first ui) 1726227535213
 ```

**Comment by abenz1267** [comment]
I can't debug nix things, but Walker isn't doing anything in regards to that by itself, since it's just GTK. Might be worth asking nix people about this.

**Comment by Ciflire** [comment]
there is no reason this would be a nix thing, i was just talking about env var in case it is useful to you and you software
if it is a gtk thing where should i report this, also whats makes you think it's gtk since no other gtk app has this issue? ags works perfectly fine and uses the same dependencies as you do i believe

**Comment by abenz1267** [comment]
Pls provided the used envvars (except the nix onces) so i can test with my iGPU.

**Comment by Ciflire** [comment]
this is my env with nix specific env var removed, i did not modified nix path or anything
[env.txt](https://github.com/user-attachments/files/17002504/env.txt)
