### ISSUE TITLE
lowering ram usage

### ISSUE THREAD

**Issue by smhd001** [abenz1267/walker#129]
I believe the RAM usage of this app, considering its functionality, is higher than expected.

While I’m not sure if it's possible, achieving RAM usage under 50MB (or even lower) would be ideal.

**Additional Context:**
For comparison, here’s how it compares against [fuzzel](https://codeberg.org/dnkl/fuzzel).

![Sc_14030630_20240920_18:33:05](https://github.com/user-attachments/assets/46d530e3-32ae-46f3-be98-07e7dd85f38a)

**Have you checked the wiki?**
Yes

**Comment by abenz1267** [comment]
Closing. This is neither a feature request nor a bug report.

Comparing memory usage of programs that use completely different tech is utterly pointless nor i something like `50MB (or even lower) would be ideal` utterly pointless. Ideal for what? Running on a smartphone?
