### ISSUE TITLE
Windows module not populating list on init.

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#133]
**Describe the bug**
When using only the 'windows' module the list is not pre-populated.

**Version**
0.7.7

**Minimal Config**
Present with the default catppuccin

**To Reproduce**
walker -m windows

**Expected behavior**
I expect the list of entries/windows to be filled without having to type anything.
Right now I need to type a character and then the list get populated.

Also happens if passing a query.
walker -m windows -q "e"

**Desktop**
 - Arch + Sway

**Comment by quadbyte** [comment]
Figured this works fine when the service is running.    Might be worth mentioning in the wiki.

**Comment by abenz1267** [comment]
I'm not even 100% sure anymore why the windows module only works when running as a service... 

It is used for contextual ranking of applications, but other than that... might be worth refactoring.
