### ISSUE TITLE
PowerMenu (custom plugin) not working as expected.

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#134]
**Describe the bug**
When using the example Power menu from the wiki, no icon is shown at the left of entries and the prompt is not filtering out results.

**Version**
0.7.7

**Minimal Config**
` "plugins": [
    {
      "name": "power",
      "placeholder": "Power",
      "switcher_only": true,
      "keep_sort": true,
      "icon": true,
      "entries": [
        {
          "label": "Shutdown",
          "icon": "system-shutdown",
          "exec": "shutdown now"
        },
        {
          "label": "Reboot",
          "icon": "system-reboot",
          "exec": "reboot"
        },
        {
          "label": "Lock Screen",
          "icon": "system-lock-screen",
          "exec": "playerctl --all-players pause & hyprlock"
        }
      ]
    }
  ]`

**To Reproduce**
install the plugin in the config file and run
walker -m power -k

**Expected behavior**
- Icons should appear to the left of entries
- Typing letters in the prompt should filter out results.

**Desktop**
- Arch + Sway

**Comment by abenz1267** [comment]
For icons to be shown when only loading up a single module, you need to specify `"show_icon_when_single": true`.

**Comment by abenz1267** [comment]
For the entries not being filtered: there's a bit of a oversight here: the entries require an "recalculate_score" to be true to get their score recalculated on typing. This should prob. be `true` by default....

**Comment by abenz1267** [comment]
module wide `"recalculate_score"` has been added so you don't have to define it for every entry.

**Comment by quadbyte** [comment]
Thanks a lot for looking into this.
For some reason the filtering is still ignored.

I'm running 
❯ walker --version
0.7.8

with the attached config.
[config.json](https://github.com/user-attachments/files/17544853/config.json)

**Comment by abenz1267** [comment]
`"keep_sort": true` => false

**Comment by quadbyte** [comment]
Thanks its working now. 
I just now figured the major difference between Walker and Rofi : Typing in the search bar in walker will not filter out invalid items (like Rofi does) , but rather reorder matching stuff on top.

I personally prefer filtering over reordering.   Could this be an option?

**Comment by quadbyte** [comment]
Awesome, thank you!   will update asap and report back.

**Comment by quadbyte** [comment]
Tested and approved!  This is such a game changer for me ;)
