### ISSUE TITLE
Label for Password Mode

### ISSUE THREAD

**Issue by Hexygo** [abenz1267/walker#135]
**Is your feature request related to a problem? Please describe.**
I was trying to setup Walker as a `SSH_ASKPASS` and  `SUDO_ASKPASS` handler.

I managed to do it but I would like to have some sort of label that tells me what I am asked to write. I would just need to have something written before writing the password. Of course I could just know what I'm doing when I'm asked the password, but it would be nice

**Describe the solution you'd like**
Label before the password input that says something that you can specify either in a theme or as a CLI argument

**Have you checked the wiki?**
Yes

**Comment by abenz1267** [comment]
`--placeholder` now works with `--password`. is that sufficient?

**Comment by Hexygo** [comment]
Thank you, i'll check later but it should be more than enough!
