### ISSUE TITLE
Clipboard module improvement to allow automatic paste in place.

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#137]
**Is your feature request related to a problem? Please describe.**
When using ROFI, I have my clipboard setup so that it pastes immediately after selection using 'wtype'.
cliphist list | rofi -dmenu  | cliphist decode | wl-copy && wtype -M ctrl -M shift v

**Describe the solution you'd like**
I would like to see a new option in the clipboard module, it could be "exec" or "post_exec"  so we can apply the treatment we want.

**Describe alternatives you've considered**
Could use the legacy dmenu way, but it is not great as it miss too many features.

**Have you checked the wiki?**
Yes?

**Comment by abenz1267** [comment]
There's an `exec` field for the clipboard module now. It defaults to `wl-copy`, but you'd just put `wl-copy && wtype -M ctrl -M shift v` in there.

**Comment by quadbyte** [comment]
This works fantastic, thank you!
