### ISSUE TITLE
Window Switcher not switching

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#139]
**Describe the bug**
Not sure if this is a bug or something with my config.

The window switcher module is not switching workspace or focusing the window I choose.
I can see on my (way)bar that the activate request went through (ie: the workspace turns red, requesting attention)  but nothing else happens.

It works fine with Rofi (in Hyprland and Sway) when using "rofi -show window"

**Version**
0.7.8

**Minimal Config**
[config.json](https://github.com/user-attachments/files/17546718/config.json)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Switching to the appropriate workspace and focusing the window.

**Desktop**
 - Arch
 - Hyprland

**Comment by abenz1267** [comment]
Hm, is there any error?

I'm also on Arch/Hyprland and it works fine for me.

**Comment by abenz1267** [comment]
Hm, thanks for the video. Weird. I have `follow_mouse = 1` in my hyprland config. Tried with `0`.. work in both cases for me.

I hate stuff I can't reproduce :joy: .

**Comment by quadbyte** [comment]
Investigated a little more.
Tried with an empty hyprland config and got the same results.

Currently using : 
Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.3

Anything I could try to help out debugging ?

**Comment by abenz1267** [comment]
Could you try with just 1 monitor? Just to eliminate some variables here...

**Comment by quadbyte** [comment]
Have the same result/bug on my laptop with a single monitor.

**Comment by abenz1267** [comment]
could you:

`pkill walker && walker --gapplication-service` and in a different terminal `walker -m windows` then switch? Check if the service instance throws an error.

**Comment by quadbyte** [comment]
Really puzzled by this. 
I tried what you suggested and got the usual Vulkan messages.

> INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 7800 XT (RADV NAVI32) priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 7800 XT (RADV NAVI32)   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message: linux_read_sorted_physical_devices: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Original order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 7800 XT (RADV NAVI32) priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      Sorted order: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:            [0] AMD Radeon RX 7800 XT (RADV NAVI32)   priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message: vkCreateDevice layer callstack setup to: priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Application> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      || priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Loader> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:      || priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:    <Device> priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk
INFO Vulkan: Loader Message:        Using "AMD Radeon RX 7800 XT (RADV NAVI32)" with driver: "/usr/lib/libvulkan_radeon.so" priority=6 code_file=../gtk/gdk/gdkvulkancontext.c code_line=1650 code_func=gdk_vulkan_debug_report glib_domain=Gdk

**Comment by quadbyte** [comment]
It's working fine in Sway!

**Comment by abenz1267** [comment]
Would you mind sharing your complete hyprland.conf?

**Comment by quadbyte** [comment]
Forgot to report that yesterday, I went ahead and installed a VM with a fresh iso  of EndeavourOS without any DE,
Then installed hyprland+kitty+walker.
Kept the default hyprland config and got the exact same issue with Walker's  windows  switcher.

Also tried hyprland-git, and also got the issue.

**Comment by quadbyte** [comment]
here is my hyprland config, but I'm convinced the problem lies somewhere else.  
[hypr.tar.gz](https://github.com/user-attachments/files/17571803/hypr.tar.gz)

**Comment by abenz1267** [comment]
Yeah, just tried with your config: works.

**Comment by abenz1267** [comment]
AArgh. I'm sorry: just looked at your walker config.... `force_keyboard_focus` doesn't play well with window switching. It needs to be `false`.

**Comment by quadbyte** [comment]
Ah! Glad you found the problem!
'force_keyboard_focus' is set to true in Walker's default config and is not really documented anywhere. 
Maybe a saner default would be to set it to false ?

**Comment by abenz1267** [comment]
I agree.
