### ISSUE TITLE
no applications?

### ISSUE THREAD

**Issue by dennkaii** [abenz1267/walker#14]
No applications shown when launching walker

![image](https://github.com/abenz1267/walker/assets/70287696/2cf1edd2-c906-4f3f-8a05-5883ecea5c1a)

yet the other modes works as intended.

I don't get any logs when launching from terminal

**Comment by abenz1267** [comment]
At first glance this looks like a broken applications cache file to me. Remove it. `$HOME/.cache/Walker/applications.json`.

This might happen when I change the caching format.

**Comment by dennkaii** [comment]
Oh, this fixed it. Tysm
