### ISSUE TITLE
"walker --version" is not responding when service is running.

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#141]
**Describe the bug**
walker --version  never returns anything if "walker --gapplication-service" was executed before hand.

**Version**
0.7.9

**To Reproduce**
In a terminal
- hyprctl dispatch exec "walker --gapplication-service"
- walker -v 

**Expected behavior**
Return the app version.

**Desktop**
 - Arch
 - Hyprland

**Comment by abenz1267** [comment]
fixed.

**Comment by quadbyte** [comment]
Built from source and confirmed it's fixed. Thanks.
