### ISSUE TITLE
Auto timeout

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#142]
**Is your feature request related to a problem? Please describe.**

I believe it would be worth it to add an auto timeout to close Walker after a fixed amount of time.
When I was using Rofi I had this in my config.

>   timeout {
      delay: 15;
      action: "kb-cancel";
  }

**Describe the solution you'd like**
Added a setting timeout_delay or similar new entry in the config with a default of zero (disabled)

**Have you checked the wiki?**
Yes?

**Comment by abenz1267** [comment]
Would you need the action? Or Just a timeout? What's the usecase here? Just so it disappears after X seconds of inactivity?

**Comment by quadbyte** [comment]
A simple timeout so it auto dismiss after the X seconds of inactivity.   No action required.

**Comment by abenz1267** [comment]
Added.

**Comment by quadbyte** [comment]
Thank you, tested and much appreciated.

**Comment by quadbyte** [comment]
Scrolling in the list of entries with the keyboard does not seem to count as activity.

**Comment by abenz1267** [comment]
Indeed rn only typing does.

**Comment by abenz1267** [comment]
Check latest release.

**Comment by quadbyte** [comment]
Talked to quickly, I'm seeing an odd behavior. Will try to report with repro steps.

**Comment by quadbyte** [comment]
Not sure if this is related, but the prompt cursor (Search...) caret stops blinking after 9 or 10 seconds.  Is this a feature ?
I believe it's a bug, because after it stops, then it seems the activity is no longer tracked so the program exits after the timeout even tho I'm still navigating the entries.

Attached a video illustrating the issue. All I do is Up/Down on the keyboard.  You can see the caret stops blinking and then it exits a bit after.

https://github.com/user-attachments/assets/0bcc2950-f17b-4466-aaee-356893f03da3

**Comment by abenz1267** [comment]
Odd indeed. I think there's a few more handlers missing... rn the timeout only respects typing and actual scrolling.

**Comment by abenz1267** [comment]
Ok, i have no idea what causes the cursor to stop blinking. It happens for me as well.

Latest commit should have fixed the timeout being ignored by the keystrokes though.

**Comment by quadbyte** [comment]
Yeah, I don't know why the caret stop blinking after 9 or 10s. Weird.

The timeout behavior is much better now.   Even tho I found one more edge case.
If I invoke  "walker"  and do not interact with it at all (no keystroke, no click, nothing)  it never timeout.

I have my timeout set at 15seconds.

**Comment by abenz1267** [comment]
Should be fixed, pls check latest release.

**Comment by quadbyte** [comment]
Sorry, forgot to go back to the issue to close.  Working good thx!
