### ISSUE TITLE
Improve plugin functionality with display column filtering.

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#145]
**Is your feature request related to a problem? Please describe.**
I'm facing multiple small issues when developing plugins.

I'd like to dissociate data (string value) presented to the user in Walker's UI and some logical key kept in the background to execute things on.

For example I wrote a tiny plugin for Hyprland to list all existing windows (clients) and offer the user to select one to close. 

I'd like to present the user with clean window's title but the code should still hold the client's address (0x123456789)  to be sure to close the exact selected windows.

![image](https://github.com/user-attachments/assets/af640879-2df6-4c3d-80ff-d574de546b16)

**Describe the solution you'd like**
Maybe like in Rofi, where you can define "-display-columns 2" to only present the 2nd columns (separated by tab) in the UI.

**Describe alternatives you've considered**
Right now I'm injecting the client's address between brackets, so I can extract it later.
 
**Have you checked the wiki?**
Yes?

Also to be noted,  "src_one_refresh: true "does not seem to trigger a refresh every time the plugin is executed, so the list of windows is stuck in the past when --gapplication-service was launcher.

My plugin :
```
{
      "name": "closewindow",
      "placeholder": "Close Window",
      "prefix": "~",
      "terminal": true,
      "src_once": "~/.local/bin/window-controller --list",
      "src_once_refresh": true,
      "cmd": "~/.local/bin/window-controller --kill '%RESULT%'"
    }
```

And attached the window-controller script (as txt so github accepts it)
[window-controller.txt](https://github.com/user-attachments/files/17606985/window-controller.txt)

Thanks a lot for your help!

**Comment by abenz1267** [comment]
A few things:

- `src_once_refresh` is deprecated. `refresh` should be used
- Walker has a `labelcolumn` and a `separator` flag, although I've only ever tested it in dmenu-mode and I'm not even sure this would help you

Walker has alternative actions you can execute, maybe adding a `close` function to the builtin windows module would be an option?

**Comment by abenz1267** [comment]
Try latest git:

- `label_column`
- `result_column`
- `separator`

added

**Comment by quadbyte** [comment]
Awesome, compiling as we speak.

BTW, Wiki's plugin page should be update (src_once_refresh)
https://github.com/abenz1267/walker/wiki/Plugins

**Comment by abenz1267** [comment]
Already updated it
