### ISSUE TITLE
`unexpected EOF` when running `--gapplication-service`

### ISSUE THREAD

**Issue by Inglan** [abenz1267/walker#146]
**Describe the bug**
When I run `walker --gapplication-service` I get this error
```
unexpected EOF
panic: unexpected EOF


goroutine 1 [running, locked to thread]:
log.Panicln({0xc000039850?, 0xab63a0?, 0xc0001c0030?})
        /opt/hostedtoolcache/go/1.23.2/x64/src/log/log.go:446 +0x5a
github.com/abenz1267/walker/internal/util.FromGob[...]({0xc0001a00c0, 0x2a}, 0xc0001c0030)
        /home/runner/work/walker/walker/internal/util/file.go:41 +0x137
github.com/abenz1267/walker/internal/modules/clipboard.(*Clipboard).SetupData(0xc000194d80, 0xc0000ecc08?, {0x0?, 0xafe2c0?})
        /home/runner/work/walker/walker/internal/modules/clipboard/clipboard.go:78 +0x6b
github.com/abenz1267/walker/internal/state.(*AppState).StartServiceableModules(0xc000286000, 0xc0000ecc08)
        /home/runner/work/walker/walker/internal/state/appstate.go:66 +0x1a6
main.main()
        /home/runner/work/walker/walker/cmd/walker.go:74 +0xd15
```

**Version**
0.8.2 (`walker-bin` from aur)

**Minimal Config**
Default config has this issue

**To Reproduce**
Execute `walker --gapplication-service`

**Expected behavior**
Walker should start in the background

**Screenshots**
N/A

**Desktop**
 - Arch Linux
 - Hyprland

**Additional context**
`walker` on its own works

**Comment by abenz1267** [comment]
Hm, this is weird. Seems to be a malformed `~/.cache/walker/clipboard.gob`.

Walker will now just error out and cleanup the file instead of panic, if a data file is broken.

**Comment by Inglan** [comment]
Just deleted everything and then reinstalled, works now
