### ISSUE TITLE
Ability to choose output/monitor

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#147]
**Is your feature request related to a problem? Please describe.**
In dual monitor setup, I would like Walker to appear only on the main screen.

**Describe the solution you'd like**
Add a new settings to choose a named output. ex: "DP-1"

**Have you checked the wiki?**
Yes?

**Comment by abenz1267** [comment]
I don't have a second monitor to try, but i've added a `monitor` setting to the config. Feel free to try it out and report back.

**Comment by quadbyte** [comment]
Hey Andrej, it is working really well.  Thank you!

Would it be possible to add environment vars support in the config.json ? or is it too much ?

Here is my use case : 
I switch between my desktop and laptop everyday and I am using very similar (Hyprland) setups. The only things that changes are monitor names and thermal_zone ids.

I have setup env vars for my primary display on both machine (ex: PRIMARY_MONITOR=DP-1)  and I use this var in Waybar and Walker to focus stuff on the main display.

For now I have to work around the issue by using envsubst to generate my final config files from templates.
cat ~/.config/walker/templates/config.json | envsubst > ~/.config/walker/config.json

Let me know what you think.
Thanks

**Comment by quadbyte** [comment]
Does not seem to work, unless my syntax is wrong.

I tried
"monitor": "$PRIMARY_MONITOR",


Here is the top of my config for reference.

```
{
  "theme": "rosepine",
  "as_window": false,
  "disable_click_to_close": false,
  "force_keyboard_focus": false,
  "ignore_mouse": true,
  "timeout": 15,
  "monitor": "$PRIMARY_MONITOR",
  "disabled": ["finder", "runner"],
  "activation_mode": {
    "labels": "1234567890"
```

**Comment by abenz1267** [comment]
I god... i misunderstood. i thought u meant overriding config vars with envvars.

**Comment by abenz1267** [comment]
But that said: can't you run walker with `$YOURENVVAR walker --gapplication server`?

**Comment by abenz1267** [comment]
I've just pushed an update which allows you to do `$MONITOR=SOMEOUTPUT walker --gapplication-service`.

This should be sufficient I guess.

**Comment by quadbyte** [comment]
Thanks a lot, it's working for me. 

For reference, I launch walker like so in Hyprland.
exec-once = MONITOR="$PRIMARY_MONITOR" walker --gapplication-service

PRIMARY_MONITOR is manually added to /etc/environement on all my computers.
