### ISSUE TITLE
Cachix doesn't work

### ISSUE THREAD

**Issue by Ciflire** [abenz1267/walker#148]
**Describe the bug**
I have to rebuild walker (about 20minutes) each time there's a new commit, this shouldn't happen as the cache is setup on my side i suspect there's something wrong with the cache

**Version**
Latest commit

**Minimal Config**
Default config

**To Reproduce**
just update and upgrade system

**Expected behavior**
To pull from the cache

**Screenshots**

**Desktop**
 - OS Nix
 - DE Hyprland

**Additional context**
I know you don't use nix, but i've already seen with the community and they don't seem to know where that comes from, if i try to `nix build` when i clone the repo it still rebuild from source. I'm pinging the people i see on the blame in the actions and the nix @diniamo @ErrorNoInternet

**Comment by Ciflire** [comment]
looks like it's working again for some reason? anyone did something or can confirm?

**Comment by abenz1267** [comment]
didn't do anything. prob. just something caused by the 3rd party cache that's being used?

**Comment by Ciflire** [comment]
It seems it's broken again
