### ISSUE TITLE
Emojis module showing double emojis

### ISSUE THREAD

**Issue by deimoss123** [abenz1267/walker#149]
**Describe the bug**
When running `walker -m emojis` it shows the same emoji 2 times. Sometimes one of them doesn't show up correctly.

**Version**
0.8.2-1 walker-bin from AUR.

**Minimal Config**
Using the default config with kanagawa theme.

**To Reproduce**
Run `walker -m emojis`, and perhaps use my computer.

**Expected behavior**
For it to show each emoji only once.

**Screenshots**
![image](https://github.com/user-attachments/assets/d28fb630-1446-4687-93ea-b66e86568239)
![image](https://github.com/user-attachments/assets/c053a7e7-d25c-42d2-be2f-66c370e9c6c1)

**Desktop**
 - OS Arch
 - DE Hyprland

**Additional context**
I have the Noto fonts and NotoColorEmoji installed, if that helps.

**Comment by abenz1267** [comment]
![image](https://github.com/user-attachments/assets/f11496ab-3383-431b-afa5-ce06b9bb7241)

The lofi once look fine on my system.

**Comment by abenz1267** [comment]
"fixed". Unqualified emojis won't be shown be default now.
