### ISSUE TITLE
Clipboard couldn't be loaded: cache malformed.

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#151]
**Describe the bug**
Clipboard no longer works . I get the following message when running: "walker --gapplication-service"

> clipboard couldn't be loaded: cache malformed.

I tried clearing everything with "walker -m commands"  to no avail.

**Version**
Walker version 0.8.4

**Desktop**
 - Arch
 - Hyprland

**Additional context**

**Comment by quadbyte** [comment]
Problem introduced at commit 50f85b0869d9d78a5cd5083097e5f47b0e19c747

If you delete clipboard.gob, clipboard module wont start.

**Comment by abenz1267** [comment]
fixed

**Comment by quadbyte** [comment]
Thank you!
