### ISSUE TITLE
Better calculator visibility heuristics

### ISSUE THREAD

**Issue by Mabi19** [abenz1267/walker#153]
**Is your feature request related to a problem? Please describe.**
The calculator module is great and I use it constantly (so I'd like to have it unprefixed), but qalc is very aggressive with returning results that I would never care about. For example, when typing "thun", I'd like Thunar to show up first, but instead I get a pointless unit conversion.
![screenshot](https://github.com/user-attachments/assets/8f1eadef-9231-429a-bcef-2f7a9627957d)

**Describe the solution you'd like**
I'd like a basic heuristic to hide the calculator results when they're obviously irrelevant - for example, when the input has no digits or operators. A manual override might be needed for the when you do want to know that thun = 6.9523450n aJ·g for some reason, though.

**Describe alternatives you've considered**
Using a prefix (for example =) would work, but I find having to type it every time I want to know what 2 + 2 is quite annoying.

**Additional context**
dis isn't discord, it's obviously i times a day times a second!
![screenshot of query "dis"](https://github.com/user-attachments/assets/e8ef8937-4b30-438e-901b-c8e4833772ac)
Thanks, I definitely wanted to know that system = 2.718281828 μg²/kPa!
![screenshot of query "system"](https://github.com/user-attachments/assets/373d1025-2a5c-4c0b-8c9c-7fd2f96323f5)

**Have you checked the wiki?**
Yes

**Comment by abenz1267** [comment]
Fixed in latest release.

**Comment by Mabi19** [comment]
Works like a charm, thanks!
