### ISSUE TITLE
Cannot copy images from browsers

### ISSUE THREAD

**Issue by IceDBorn** [abenz1267/walker#154]
Ex. Copying images from firefox results in the clipboard having entries like `<meta http-equiv="content-type" content="text/html; charset=utf-8"><img src="https://proxy.piped.knp.one/vi_webp/4qDYa2aIBxw/maxresdefault.webp?host=i.ytimg.com" alt="https://proxy.piped.knp.one/vi_webp/4qDYa2aIBxw/maxresdefault.webp?host=i.ytimg.com">`

**Comment by IceDBorn** [comment]
Is there a way for me to use this "dirty" solution with walker? Also, if I copy an image twice, then it gets copied as an image to my clipboard correctly.

**Comment by abenz1267** [comment]
No, not really. I'll implement a dirty hack shortly.

For the copying-twice thingy: walker stores a hash of the copied whatever and checks if it's already present. The mechanism isn't good.

**Comment by abenz1267** [comment]
I've pushed a fix that at least doesn't break copying images from browser anymore.
