### ISSUE TITLE
When use alt + enter to use a comand give the terminal who open a custom title

### ISSUE THREAD

**Issue by Wateir** [abenz1267/walker#157]
**Is your feature request related to a problem? Please describe.**
I want to have a float windows when i use alt enter for a command

**Describe the solution you'd like**
Use a custom tittle for the windows, and write a windows rule on my hyprland config

**Describe alternatives you've considered**
none sorry

**Additional context**
nop

**Have you checked the wiki?**
Yes of course

**Comment by abenz1267** [comment]
If force-opening in a terminal it'll now put `--title WalkerRunner`
