### ISSUE TITLE
Show desktop actions when need

### ISSUE THREAD

**Issue by Wateir** [abenz1267/walker#158]
**Is your feature request related to a problem? Please describe.**
When i open walker i want to just have desktop app, and not all desktop actions who can come with my app

**Describe the solution you'd like**
if empty search: no desktop actions
if not empty: desktop actions

**Describe alternatives you've considered**
Nop

**Have you checked the wiki?**
Yes

**Comment by abenz1267** [comment]
i've added an option. it's true by default.
