### ISSUE TITLE
Walker stucks in buildPhase on NixOS

### ISSUE THREAD

**Issue by Flexksx** [abenz1267/walker#159]
**Describe the bug**
When trying to install on NixOS using the flake and home-manager config, walker will get stuck in the building phase.
It will update everything and when it gets to building walker, it will show this in the terminal
```
[1/2/8 built, 0.0 MiB DL] building walker-0.9.7-git (buildPhase): Building subPackage ./cmd/walker.go
```
And will get stuck for a long time, and I cancel the installation and revert the changes in the config.
**Version**
walker-0.9.7-git

**Minimal Config**
in the home-manager config
```nix
programs.walker = {
    enable = true;
    runAsService = true;
  };
```
**To Reproduce**
Follow the 2nd option for installing it on NixOS, add
```nix
inputs.walker.url = "github:abenz1267/walker";
```
And in the import section of home-manager add 
```nix
inputs.walker.homeManagerModules.default
```
Update your system. I update it with an alias
```nix
sudo NIXPKGS_ALLOW_UNFREE=1 nixos-rebuild switch --flake /home/flexksx/nixos-config/nixos#nixos
home-manager switch --flake /home/flexksx/nixos-config/nixos/#flexksx@nixos
```
**Expected behavior**
Have walker installed

**Desktop**
- OS NixOS
- DE Hyprland

**Comment by Flexksx** [comment]
The same happens if I add walker to 
```nix
environment.systemPackages
```
or
```nix
home.packages
```

**Comment by abenz1267** [comment]
It takes a long ass time to build. How long did you wait? For reference: with my 7950x it takes around 6 minutes to build.

You can always use the build cache.

I don't use nix, so that's all the support i can give.

**Comment by Flexksx** [comment]
Hmm ok I'll try again then, I waited around 2 minutes and I thought there's a problem with it, because it didn't log anything. I'll try again and let you know, thanks!

**Comment by Flexksx** [comment]
Ok it took a total of about 30 minutes for it to build :) 
Thanks!

**Comment by abenz1267** [comment]
30 minutes is actually wild. No way for you to use the build-cache?

**Comment by Flexksx** [comment]
Nah it isn't a big deal, just seemed strange that it build so long. Just didn't think that my R7 4800 is so weak in comparison to a 7950X lol :)

**Comment by abenz1267** [comment]
Yeah, it's because of the C GTK stuff.

See here: https://github.com/golang/go/issues/9887#issuecomment-913056050 .

Maybe it'll get better at one point.
