### ISSUE TITLE
Move nix files into a nix directory

### ISSUE THREAD

**Issue by schromp** [abenz1267/walker#16]
The top level directory is getting quite cluttered with nix files. Even more so if my module [pr](https://github.com/abenz1267/walker/pull/15) gets merged.
It may make sense to move more files into a nix/ directory.

One downside i can see is that having the default.nix (for the package) and the shell.nix for developing inside the nix folder would make it more cumbersome for non flake users.
However, this repo is only packaged in flakes at the moment so most/all of the people that would utilize these files can do so through the flake.

As @diniamo is the one who implemented all the nix things until now he might have an opinion about this.

**Comment by diniamo** [comment]
No, I prefer to have it this way, especially until we don't have a home-manager module.

I imagine there might be edge cases where having the package as defaul.nix, and the shell as shell.nix is helpful.

**Comment by diniamo** [comment]
Ah, your pr adds the home-manager module... well I'd prefer to have only that in a separate directory.

**Comment by schromp** [comment]
Sounds good :)

**Comment by abenz1267** [comment]
closed by #15
