### ISSUE TITLE
Custom web search

### ISSUE THREAD

**Issue by varac** [abenz1267/walker#160]
**Is your feature request related to a problem? Please describe.**

I'd like to create custom web searches, i.e. search for Debian packages with `https://search.debian.org/cgi-bin/omega?P=%RESULT%`.

**Describe the solution you'd like**

An easy way to create a plugin config which lets me do this.
Maybe it's already possible, but the  https://github.com/abenz1267/walker/wiki/Plugins options are not well documented.

**Describe alternatives you've considered**

- I got this working with ulauncher

**Additional context**

Thanks for walker, I like it ! 

**Have you checked the wiki?**

Yes!

**Comment by abenz1267** [comment]
I'll extend the websearch module to allow for custom entries. Will be ready later.

**Comment by abenz1267** [comment]
```json
      "custom": [
        {
          "name": "Debian Search",
          "url": "https://search.debian.org/cgi-bin/omega?P=%TERM%"
        }
      ]
```

Would result in 

![image](https://github.com/user-attachments/assets/82040177-d5b9-4cf4-b072-944ea3e8411d)

Would that be fine?

**Comment by abenz1267** [comment]
I was thinking about adding prefixes like f.e. `deb:somepackage` or `goo:mysearch`

**Comment by varac** [comment]
This looks awesome, looking forward to test it.

**Comment by abenz1267** [comment]
You can install 0.9.7.

I completely changed the websearch module

You can do this in your config:

```json
    "websearch": {
      "entries": [
        {
          "name": "Google",
          "url": "https://www.google.com/search?q=%TERM%",
          "prefix": "go:",
          "switcher_only": true
        },
        ...
```

This would let you search google in walker by doing `go:mysearch`. You can setup your debian search this way.

**Comment by varac** [comment]
Wow, that was fast :rocket:  I'll try it once 0.9.7 got released

**Comment by abenz1267** [comment]
it's released.

**Comment by varac** [comment]
And already a 0.9.7 AUR package, nice. Works like it should, thanks !
