### ISSUE TITLE
Information about AI module

### ISSUE THREAD

**Issue by emilnymann** [abenz1267/walker#161]
I've been watching the changelog pretty closely, and the AI features sound exciting, but I have no idea how to use them. I think it would be helpful to add some information about that to the wiki or readme.

**Comment by abenz1267** [comment]
https://github.com/abenz1267/walker/wiki/Modules#ai

..enough?

**Comment by emilnymann** [comment]
That's perfect, thank you very much for that and of course for Walker itself!
