### ISSUE TITLE
Colors not being used when importing them from another style sheet

### ISSUE THREAD

**Issue by BBFifield** [abenz1267/walker#162]
**Describe the bug**
Colors aren't used when Importing them from a style sheet into your main style sheet, however, the colors will work if you define them at the top of the main style sheet instead.

**Version**
Walker 0.9.8-git

**Minimal Config**
colors.css:

```
:root {
  --base00: #303446;
  --base01: #292c3c;
  --base02: #414559;
  --base03: #51576d;
  --base04: #626880;
  --base05: #c6d0f5;
}

```
style.css:

```
@import url("colors.css");

#box {
  all: unset;
  background: var(--base00);
  padding: 16px;
  border-radius: 8px;
  box-shadow:
    0 19px 38px rgba(0, 0, 0, 0.3),
    0 15px 12px rgba(0, 0, 0, 0.22);
}

```
**To Reproduce**
Select the corresponding theme and you'll see that the colors aren't applied from the imported style sheet

**Expected behavior**
Expected the colors to be applied without problems.

**Desktop**
NixOS Unstable
Hyprland

**Additional context**
The issue is present in both 0.7.7 and the latest 0.9.8-git

It also won't work if you use the gtk specific (now deprecated) way of defining colors like `@define-color base00 #303446;` with `background-color: @base00;`

**Comment by abenz1267** [comment]
Use an absolute path for the file.

**Comment by BBFifield** [comment]
> Use an absolute path for the file, like this:
> 
> ```
> @import url("file:///home/andrej/.config/walker/themes/colors.css");
> ```

That did it, thanks!
