### ISSUE TITLE
Empty actions are displayed when actions are disabled

### ISSUE THREAD

**Issue by JaCoB1123** [abenz1267/walker#164]
**Describe the bug**
When I set applications.actions to false in my config, I get "empty" entries for the applications that provide actions. For example Firefox is shown correctly once and once without title and function (i.e. does nothing, when I start it).

**Version**
0.7.7

**Minimal Config**
```
{
  "builtins": {
    "applications": {
      "actions": false,
      "name": "applications",
      "placeholder": "Applications",
    }
  }
}
```

**To Reproduce**
Start Walker

**Expected behavior**
Only main apps are shown and no empty entries.

**Screenshots**
![image](https://github.com/user-attachments/assets/8fb33d19-368b-4c7a-893d-fd7e328f1503)

**Desktop**

- NixOS 
- Niri

**Additional context**
I guess the issue lies in https://github.com/abenz1267/walker/blob/82b106e1632d1c584723b29f5979891861d36858/internal/modules/applications.go#L290C1-L292C8 as skip is set to true, but the action is still added to the slice.

**Comment by abenz1267** [comment]
Update.
