### ISSUE TITLE
Remember the previous query

### ISSUE THREAD

**Issue by flytaly** [abenz1267/walker#165]
Please, add an option to remember the previous query.

It's very handy when you need to store temporary data. Like, calculate number 1 + number 2, hide the walker, restore the walker and continue the calculation.

In fact, in Windows **PowerToys Run** for example, this is the default behavior that you need to explicitly opt out of.

![run](https://github.com/user-attachments/assets/879a8a71-9ea5-4ddf-bde5-e2572887494f)

**Comment by abenz1267** [comment]
Yeah, i can add this.

I don't want this to be the default behaviour though, or non-explicit behaviour at all. 

I'd probably add a keybind `ctrl+p` (that's the one to resume last AI session as well) that'd resume last query. Would that be ok?

**Comment by abenz1267** [comment]
Thinking about it: if it would be default to resume the last query... under what circumstances? I'd assume only if you didn't activate an item, right? But what if you activate the calc entry to copy the result?

**Comment by flytaly** [comment]
> I'd probably add a keybind `ctrl+p` (that's the one to resume last AI session as well) that'd resume last query. Would that be ok?

Yeah, it would be ok.

> Thinking about it: if it would be default to resume the last query... under what circumstances? I'd assume only if you didn't activate an item, right? But what if you activate the calc entry to copy the result?

I don't think it should be default. 
But I see a use case where clearing on activation isn't ideal.
Search for notes. (I'm using [zk plugin](https://gist.github.com/flytaly/e278d4e6592cb7e5ad646be16d042c08))
Search => open note => Oh, it's a wrong note => Open search again => Select another entry.

But it's not a big deal anyway. Restoring with ctrl+p would be enough for me.

**Comment by flytaly** [comment]
Thanks. It works!

**Comment by abenz1267** [comment]
I've just added an option to the search config `resume_last_query` (default: false).

**Comment by JuanM04** [comment]
Hey, it would be nice if this option comes back. I know there is a shortcut, but along that, I think there should be a way to always resume when walker opens.

I'm not sure about the name, but "remember partial query" or something like that. So, when you close walker without selecting anything, the query will persist the next time you open walker.

Also, following the PowerToys example, it should open with the previous query text selected. That way, you could start typing right away and clear it or press the arrows to unfocus
