### ISSUE TITLE
Binary Cache not working

### ISSUE THREAD

**Issue by Permafrozen** [abenz1267/walker#166]
**Describe the bug**
The Cachix Binary is not being used. I am unsure if I made an  configuration error, but I tried to out both caches.

**Version**
Walker version: `walker-0.10.2-git`

**Minimal Config**

I included Cachix as my subsituter for the binary:
```nix
  nix.settings = {
    substituters =
      [ "https://walker-git.cachix.org" ];
    trusted-public-keys = [
      "walker-git.cachix.org-1:vmC0ocfPWh0S/vRAQGtChuiZBTAe4wiKDeyyXM0/7pM="
    ];
  };
```

I used the example Configuration:

```nix
programs.walker = {
      enable = true;
      runAsService = true;

      # All options from the config.json can be used here.
      config = {
        search.placeholder = "Search";
        ui.fullscreen = true;
        list = { height = 200; };
        websearch.prefix = "?";
        switcher.prefix = "/";
      };

      # If this is not set the default styling is used.
      # style = #''
      #   * {
      #     color: #dcd7ba;
      #   }
      # '';
    };
```

**To Reproduce**
1. Use configuration and add to flake
2. Rebuild
3. My CPU is melting because :(

**Expected behavior**
I expected the binary cache to be used, so I don't need to build anything myself.

**Screenshots**

**Desktop**

- OS: NixOS
- DE: Hyprland

**Additional context**
I also tried using both caches, but that also didn't seem to change anything.

**Comment by IceDBorn** [comment]
I think that you have to rebuild your system once with the substituters and then include walker in your packages

**Comment by ibrokemypie** [comment]
still running into this myself, even after building with both substituters set before enabling walker. I think this might be due to using the home manager package?

building locally would be fine if it didn't build with only one core, taking over 20 minutes.

**Comment by tsawhill** [comment]
Also running into this using the home manager module. The substituters and keys are configured and active in my current generation, yet it still seems to be building each new version.
