### ISSUE TITLE
Icons color is no longer following text color

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#167]
**Describe the bug**
Icon color has changed since a recent update.

**Version**
0.10.3

**Minimal Config**
Using this custom module with the default theme.
```
{
      "name": "power",
      "placeholder": "Power",
      "switcher_only": true,
      "recalculate_score": true,
      "show_icon_when_single": true,
      "keep_sort": false,
      "entries": [
        {
          "label": "Lock Screen",
          "icon": "system-lock-screen",
          "exec": "playerctl --all-players pause & hyprlock"
        },
        {
          "label": "Log Out",
          "icon": "system-log-out",
          "exec": "loginctl terminate-user $(whoami)"
        },
        {
          "label": "Shutdown",
          "icon": "system-shutdown",
          "exec": "shutdown now"
        },
        {
          "label": "Reboot",
          "icon": "system-reboot",
          "exec": "reboot"
        }
      ]
    },
```

**To Reproduce**
walker -m power

**Expected behavior**
Icons used to have the same color as text, now they are grey (might be transparent)

**Screenshots**
![image](https://github.com/user-attachments/assets/4979af38-2aa4-417a-a6c8-a576dde54947)

**Desktop**

- OS Arch
- DE Sway or River.

**Additional context**
Do you know what css class I should target?

**Comment by abenz1267** [comment]
CSS selector is just `#icon`. What icon theme is that?
