### ISSUE TITLE
Scrollbar showing up even with "v_scrollbar_policy": "never"

### ISSUE THREAD

**Issue by Lau-San** [abenz1267/walker#168]
**Describe the bug**
Even with `"v_scrollbar_policy": "never"`, scrollbar is still showing up.

**Version**
0.10.3

**Minimal Config**
Scroll config (this was working before I updated):
```json
{
    "ui": {
        "window": {
            "box": {
                "scroll": {
                    "v_scrollbar_policy": "never"
                }
            }
        }
    }
}
```

**To Reproduce**
- Set "v_scrollbar_policy" setting to "never"
- Launch walker with the theme

**Expected behavior**
The scrollbar shouldn't appear.

**Screenshots**

![image](https://github.com/user-attachments/assets/36343f9c-7b0d-4423-9d5a-fe3c337fd864)
![image](https://github.com/user-attachments/assets/ccea04c7-8cb7-4168-beff-d382a248c1d9)

**Desktop**

- OS: EndeavourOS
- DE: Hyprland

**Additional context**
[Full theme config file](https://pastebin.com/eawCBZ6T)

**Comment by abenz1267** [comment]
Should be fixed in git.

**Comment by Lau-San** [comment]
Yup, scrollbar's gone now!
