### ISSUE TITLE
Strange bottom padding on list items

### ISSUE THREAD

**Issue by Lau-San** [abenz1267/walker#170]
**Describe the bug**
After upgrading to 0.10.4 from 0.10.3, there's a weird bottom padding on list items that I can't seem to get rid of.

**Version**
0.10.4

**Minimal Config**
Config that I think may be related:
```json
{
    "ui": {
        "window": {
            "v_align": "fill",
            "box": {
                "orientation": "vertical",
                "v_align": "start",
                "scroll": {
                    "v_align": "start",
                    "v_expand": false,
                    "list": {
                        "item": {
                            "spacing": 18,
                            "wrap": false,
                            "text": {
                                "h_align": "fill",
                                "h_expand": true,
                                "revert": true,
                                "label": {
                                    "wrap": false
                                },
                                "sub": {
                                    "hide": true
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

```

[Theme config](https://pastebin.com/e3tyS7Rb)

[Theme CSS](https://pastebin.com/WnCcirGH)

[Walker config](https://pastebin.com/NRxQnu4Q)

**To Reproduce**
- Set theme config shown above

**Expected behavior**
Each item should have the same space top and bottom.

**Screenshots**

How it looked before update:

![image](https://github.com/user-attachments/assets/d0c9195d-3478-4ee3-8c15-e3d32f7627df)

How it looks now:

![image](https://github.com/user-attachments/assets/778eb88c-7c84-40df-9dfe-54398075e561)

**Desktop**

- EndeavourOS
- Hyprland

**Additional context**

Launched with `env GTK_DEBUG=interactive` to inspect it and didn't see any strange margin or padding being applied, but I changed the first `child`'s `valign` property from "GTK_ALIGN_FILL" to "GTK_ALIGN_START" and it fixed the size, but it left a space anyway:

![image](https://github.com/user-attachments/assets/a7fd1e34-6792-46fc-a9e9-9f6bed8d8b35)

Not sure if that helps, but thought I'd mention it...

**Comment by abenz1267** [comment]
Hi,

i found the cause:

1) the scrollbar policies have been swapped accidentally => this is fixed
2) if you are not on git and on 0.10.4 => swap your v_scrollbar_policy and your h_scrollbar_policy
3) (true) v_scrollbar_policy should NOT be "never"
4) if you want to hide the scrollbar visually => do it via css ( `opacity: 0` )

**Comment by Lau-San** [comment]
> Hi,
> 
> i found the cause:
> 
>     1. the scrollbar policies have been swapped accidentally => this is fixed
> 
>     2. if you are not on git and on 0.10.4 => swap your v_scrollbar_policy and your h_scrollbar_policy
> 
>     3. (true) v_scrollbar_policy should NOT be "never"
> 
>     4. if you want to hide the scrollbar visually => do it via css ( `opacity: 0` )

Just updated to 0.10.5 and changed v_scrollbar_policy to "automatic", now it works perfectly. Thanks!
