### ISSUE TITLE
Absurd behavior in rare scenarios

### ISSUE THREAD

**Issue by fdev31** [abenz1267/walker#171]
**Describe the bug**

Sometimes, walker doesn't even select exact matches (in dmenu mode)

**Version**
0.10.5

**Minimal Config**
`echo -e "󰜎 ticket (open)\nCPE" | walker -d -k`

**To Reproduce**

type "CPE" which is an exact match and observe: it's not getting selected.

**Expected behavior**

When I search for "CPE", the "CPE" entry should be selected.

**Desktop**

- Arch
- Hyprland

**Comment by abenz1267** [comment]
Could reproduce. Will look into it. Thanks for reporting.

**Comment by abenz1267** [comment]
Ok, this is caused by the `-k` (keep_sort) flag. it will literally keep the sorting order of the entries. i made it so that it properly sorts by rank if the search query isn't empty.

**Comment by abenz1267** [comment]
feel free to check latest release.

**Comment by fdev31** [comment]
It is fine now, thank you for being so reactive!

**Comment by fdev31** [comment]
Unfortunately, I still see -k is not working, order isn't preserved, leading to unexpected behavior, another scenario:

`echo -e "Jira ticket (open)\nJira cheat sheet" | walker -k -d`

Type "Ji" or "ji: the order is swapped.

**Comment by abenz1267** [comment]
Yeah, the problem here is:

Both entries end up having the same fuzzy score => the sorting resolves to sorting alphabetically.

I made it so that keep_sort will NOT resolve to sorting alphabetically, if 2 entries end up having the same score. This would still re-order based on score though.

**Comment by fdev31** [comment]
And it's already available on arch, it rocks, thanks, closing again :)
