### ISSUE TITLE
Delete/Block Items from the clipboard

### ISSUE THREAD

**Issue by crispy-caesus** [abenz1267/walker#172]
**Is your feature request related to a problem? Please describe.**
I sometimes have to copy passwords, and thus they end up in the clipboard history in walker.
I don't know if it's a huge issue, but it would feel better if I could remove it from that/block it.

**Describe the solution you'd like**
It would probably make the most sense to just delete with Shift+Backspace like in the normal app launcher.

**Describe alternatives you've considered**
I'm not sure if some sort of blacklist stored in some way outside of the walker config could make sense, to not add certain items to the clipboard history in the first place.

If there's some way clipboard items get tagged natively, that they're a secret, that could just be used too.

**Have you checked the wiki?**
Yes?

**Comment by abenz1267** [comment]
Sadly `CLIPBOARD_STATE` is not working as expected, so deleting entries via `shift+backspace` seems to be the most viable solution.

Added in 0.10.9.

**Comment by abenz1267** [comment]
... is this solved?

**Comment by abenz1267** [comment]
closing. Feel free to re-open if this isn't solved.
