### ISSUE TITLE
Smarter focus handling

### ISSUE THREAD

**Issue by fdev31** [abenz1267/walker#173]
**Is your feature request related to a problem? Please describe.**
When opening walker, depending on the window manager setup, the mouse cursor will be hovering the center of the window. This is conflicting with the keyboard / first item selection and creates some flickering on top of selecting some unwanted item.

**Describe the solution you'd like**
While typing in walker, if the mouse cursor is hovering the window, I would like the selection to behave as if there was no mouse cursor, unless the cursor is moving.

**Describe alternatives you've considered**
Completly ignore mouse events for some short amount of time when the list refreshes.

**Additional context**
While typing the selection goes to the first item and then (incorrectly) selects the item under the mouse cursor, even though no movement was performed.

**Have you checked the wiki?**
Yes?

**Comment by abenz1267** [comment]
Is `"ignore_mouse": true` not sufficient?

**Comment by fdev31** [comment]
But then it's impossible to use the mouse at all... I can consider it as a workaround but it feels "limited".

**Comment by fdev31** [comment]
Actually I followed your recommendation since there is no better option at the moment, but got very confused by the behavior:

- mouse doesn't work AT FIRST
- as soon as there is a result it may re-activate, so the behavior is still "jumpy"

**Comment by abenz1267** [comment]
what module are you testing with? If it's anything that supports drag&drop, that's expected.

**Comment by abenz1267** [comment]
Also: it doesn't SELECT the item under the cursor. It just hovers it.

You can remove mouse hover style via css

```
child:hover:not(:selected) {
  background: unset;
}
```

**Comment by abenz1267** [comment]
This is weird. With `ignore_mouse` it should even fire a hover event at all.

Can you try latest git?

**Comment by fdev31** [comment]
(arch user here) I don't see an AUR package for it but I can eventually write a PKGBUILD later today.

**Comment by fdev31** [comment]
Ok, now with ignore_mouse it works as expected (I guess), but then the mouse is fully ignored ;)

**Comment by abenz1267** [comment]
Ok, checkout latest git. And feel free to not use "ignore_mouse".

Now: mouse will be ignored on any kinda searching (also initial opening..) UNTIL you actually move it.

**Comment by abenz1267** [comment]
Released on AUR.

**Comment by fdev31** [comment]
I think I can't complain anymore ;)
**Thank you** for the fast improvements!
FYI I added Walker as a first class (d)menu provider in pyprland (in case you are an Hyprland user):
 https://github.com/hyprland-community/pyprland/commit/02b14b742eaf56473f3875808631dec2e672ae35
