### ISSUE TITLE
Running go build fails with `file too long` message

### ISSUE THREAD

**Issue by AdelSehic** [abenz1267/walker#178]
**Describe the bug**
runing go build fails with the message

**Version**
master branch

**To Reproduce**
follow compile guide from readme

**Expected behavior**
project is built

**Desktop**

- OS Ubuntu 24.10)
- DE Hyprland

**Additional context**❯ go build -x -o walker
WORK=/tmp/go-build1554271642
-> unzip /home/adel/go/pkg/mod/cache/download/github.com/davidbyttow/govips/v2/@v/v2.15.0.zip: open /home/adel/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.15.0/resources/jpg-24bit-icc-adobe-rgb.TransformICCProfileWithFallback_RGB_source_with_ICC-linux-jammy_amd64_libvips-8.12.1-Wed Feb  2 14-43-28 UTC 2022.golden.jpeg: file name too long
../internal/ui/ui.go:19:2: unzip /home/adel/go/pkg/mod/cache/download/github.com/davidbyttow/govips/v2/@v/v2.15.0.zip: open /home/adel/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.15.0/resources/jpg-24bit-icc-adobe-rgb.TransformICCProfileWithFallback_RGB_source_with_ICC-linux-jammy_amd64_libvips-8.12.1-Wed Feb  2 14-43-28 UTC 2022.golden.jpeg: file name too long

**Comment by abenz1267** [comment]
This is not an issue with Walker directly, but rather `davidbyttow/govips`.

Nothing I can do anything about. It builds fine on Arch, Nix and the Github pipeline.
