### ISSUE TITLE
gtk4-layer-shell not supported

### ISSUE THREAD

**Issue by I-Own-You** [abenz1267/walker#180]
**Describe the bug**
I installed walker but cant run it

**Version**
0.10.15

**Minimal Config**
default config, nothing changed

**To Reproduce**
1. paru -S walker
2. paru -S walker-bin
3. build from source(git repository)

**Expected behavior**
at least to run the app

**Screenshots**
![image](https://github.com/user-attachments/assets/371002da-7d0b-46ad-a545-a504978e43e6)
![image](https://github.com/user-attachments/assets/1ca16991-d881-4ed1-9b8a-6620d85f58a6)
![image](https://github.com/user-attachments/assets/61ba90ab-445e-47e2-a061-54f6bbeba08a)
![image](https://github.com/user-attachments/assets/dd4423ff-edc9-48c3-b474-fab8c3eca106)

**Desktop**

- OS = ARCH
- DE = GNOME

**Additional context**
1. go installed
2. gtk4 installed
3. gtk4-layer-shell installed
4. gobject-introspection installed

**Comment by abenz1267** [comment]
According to https://github.com/wmww/gtk4-layer-shell gnome on wayland doesn't support gtk4-layer-shell.

Sorry!
