### ISSUE TITLE
Docs request: how to use clipboard / modules?

### ISSUE THREAD

**Issue by rektide** [abenz1267/walker#182]
**Is your feature request related to a problem? Please describe.**

Hi, I've build and started Walker. But I think all I see is a list of applications? How do I use other modules?

**Describe the solution you'd like**

Would love documentation talking about how to use other modules.

**Describe alternatives you've considered**

**Additional context**

**Have you checked the wiki?**
Yes?

**Comment by abenz1267** [comment]
Hi,

the documentation on how to use other modules isn't very good/non-existant. As self-explanatory as i think it was, apparently it isn't!

You have various ways of using modules:

- most modules are "switcher_only" by default
- use the switcher module (default prefix is `/`) to choose another module
- run `walker --modules <modules>`

So in case of the clipboard:
- open walker
- `/` => choose `clipboard`

or

`walker -m clipboard`

**Comment by zjeffer** [comment]
I'm a bit confused on how to use the 'switcher module'. I want to launch walker with multiple modules, for example:
```
walker --modules applications,ai,commands,ssh
```
When walker opens, I'm looking at the application list but I don't understand how I can now switch to 'ai', for example. Typing `/` doesn't seem to do anything. 
If I launch walker without `--modules`, `/` works fine.

**Comment by abenz1267** [comment]
If you launch walker with explicit modules via `--modules`, you don't have to switch to any. The switcher module is prefixed with `/`. You need to also load it, to access it. It is mostly used to switch to modules that are `switcher_only`. Each modules can be configured to be that...or not.

A lot of modules are switcher only by default.

Every module that isn't, is queried. Explicitly loaded modules are all queried.

For the ai module you need to setup prompts. There should be one default called "assistant". You can search for it, it should come up.

**Comment by abenz1267** [comment]
You only need to switcher to switch to modules that aren't loaded up.

**Comment by zjeffer** [comment]
I understand now, I didn't realize `switcher` was a separate module that had to be loaded to be able to switch ;) 
Looks like I finally found a rofi replacement, thanks!
