### ISSUE TITLE
Panic on none regular disk environments

### ISSUE THREAD

**Issue by ferrreo** [abenz1267/walker#185]
**Describe the bug**
Looks like the djherbis times lib doesn't like getting the "birthtime" of things on readonly/exfat/overlayfs/squashfs/live media. On my distro's live ISOs walker crashes out on startup with the following error:

![image](https://github.com/user-attachments/assets/245bec6b-26c0-4e04-8634-33310e54a46e)

it is fine once on a regular running system 

**Version**
0.10.4

**Minimal Config**
Default config

**To Reproduce**
Try to use walker on a squashfs based live usb/cd

**Expected behavior**
Should just open and not panic

**Desktop**

- OS PikaOS
- DE Hyprland

**Comment by abenz1267** [comment]
should be fixed in 0.10.20.

**Comment by abenz1267** [comment]
...can this be closed?

**Comment by ferrreo** [comment]
Will check this evening, sry was not at home.

**Comment by ferrreo** [comment]
Can't get .20, .21 or .22 to build.

https://git.pika-os.com/wm-packages/walker/actions/runs/19 log for reference. It runs in a fresh docker container.

Have there been any dep/mod changes since .13 that might need the build deps altering in my packaging?

**Comment by abenz1267** [comment]
The last change to deps was in 0.10.11 when starting to use vips.

That log doesn't tell me the error either, i must be blind.

**Comment by ferrreo** [comment]
Yeah I don't understand it, it's like it just gives up. There have been no changes to our build scripts or the build container/packages though since .13 that worked fine.

**Comment by ferrreo** [comment]
It was libvips-dev missing, removing -x from the build flags made it easier to see the real error.

.22 no longer crashes on ISOs so closing. Thanks for the prompt fix!
