### ISSUE TITLE
Fuzzy matching color gets printed out

### ISSUE THREAD

**Issue by Hexygo** [abenz1267/walker#186]
**Describe the bug**
I tried to run the command `walker -y` and the output produced by Walker includes the string "#1BEFFE1" followed by the string I input in password mode. 
This looks to be the color used for the fuzzy matching, introduced in the last version.

After further testing i verified that this is the case even just if you run Walker by itself.

**Version**
0.10.19

**Minimal Config**
Default config

**To Reproduce**
Run `walker` and redirect the output to a file, then read the contents of said file.
Oneliner: `walker > test.txt | cat test.txt`

**Expected behavior**
The string "#1BEFFE1" should not be printed in any case, especially for password input: this completely breaks the functionality, because the presence of said string, automatically causes the password to be wrong.

**Desktop**

- OS Arch
- DE Hyprland

**Comment by Hexygo** [comment]
I think i found the line that was causing the issue, opened a PR

**Comment by abenz1267** [comment]
Ups + thanks!
