### ISSUE TITLE
Add a configurable way to modify the command spawned when lauching applications

### ISSUE THREAD

**Issue by Brandoxx** [abenz1267/walker#188]
**Is your feature request related to a problem? Please describe.**
It is more of an inconvenience. With UWSM, ideally every process should be started as a systemd unit; this is done by using the command "uwsm app -- $myApp"

**Describe the solution you'd like**
A way to modify the command spawned when launching an app in the config.json file.

**Describe alternatives you've considered**
Modifying source. This gets really annoying after some time

**Additional context**
Nope

**Have you checked the wiki?**
Yes

**Comment by abenz1267** [comment]
You can use `"use_uwsm": true` to achieve that for uwsm.

**Comment by abenz1267** [comment]
I've replaced that specific config option with a more generic `app_launch_prefix` you can define yourself.
