### ISSUE TITLE
Walker can't open terminal desktop entries with Wezterm

### ISSUE THREAD

**Issue by ManuelBotas** [abenz1267/walker#189]
**Describe the bug**
When attempting to run a desktop entry for a terminal program (e.g. btop, neovim, vim, etc), it doesn't open with Wezterm.

**Version**
0.10.20

**Minimal Config**
My config is very similar to the default, but I don't believe this is related to config issues.

**To Reproduce**
1. Have Wezterm installed
2. Have some terminal app with a desktop entry, like the ones I presented above
3. Run Walker
4. Try to open one of those desktop entries

**Expected behavior**
The terminal apps open in Wezterm like they should

**Screenshots**

https://github.com/user-attachments/assets/68dd706e-93cc-4e44-be87-7f34fcc456bc

**Desktop**

- OS: Arch
- DE: Hyprland

**Additional context**
I looked around in the source code and I believe the problem is around lines 570-580 of internal/ui/interactions.go:
```go
if cfg.Terminal != "" {
    if entry.Terminal || forceTerminal {
        toRun = fmt.Sprintf("%s --title %s -e %s", cfg.Terminal, "WalkerRunner", toRun) // This is the problematic line
    }
} else {
    log.Println("terminal is not set")
    return
}
```
It's a very specific issue that most other terminals aren't affected by, but Wezterm is. The issue is that Wezterm does not have a `--title` cli option, so it just fails:
![image](https://github.com/user-attachments/assets/8194b407-be8d-4eb1-a0d5-31b04c295bcf)
I first noticed this was happening because I still had Kitty installed, and when I tried to open the btop desktop entry, I noticed it had opened with Kitty (which does have a `--title` option) instead of Wezterm. After that I uninstalled Kitty (because I hadn't been using it for a while) and tried again, which gave me the results shown in the video: the apps don't get opened with Wezterm.

**Comment by ManuelBotas** [comment]
Some extra stuff I investigated related to this:
I also checked the list of terminals in internal/config/config.go, to see if other terminals also have this issue, and I found a bunch that may also potentially have it:
- aterm
- guake
- konsole
- qterminal
- rxvt
- st
- tilda
- urxvt
- xterm

But I didn't really test too much, I just went the somewhat lazy route and looked up their man pages online on [manned.org](https://manned.org/) and I don't know how accurate they are in terms of having absolutely every possible option for the terminals. Some of them do seem to provide a similar option, but it's a `-title` instead of a `--title`, in which case I'm not sure if they're "aliased" or something. And I didn't take into account that they may not even fail with a bad title option (Wezterm does).

Sorry for the ramble, this is why I put it in a comment instead of the issue.

**Comment by abenz1267** [comment]
Thanks for the investigation, i'll implement a proper map for each terminal to check if the option can even be set and if so how. That should fix the issue.

**Comment by abenz1267** [comment]
I've added a "terminal_title_flag" config option, which is empty by default. So you can define `terminal_title_flag = "--title WalkerRunner"` by yourself now.... or whatever your terminal needs.
