### ISSUE TITLE
Locale text not being preferred

### ISSUE THREAD

**Issue by androw** [abenz1267/walker#192]
**Describe the bug**
Locale text from .desktop are not always preferred.

**Version**
0.11.0

**Minimal Config**
locale : "fr_FR" or default config with $LANG set

**To Reproduce**
- Run walker in applications mode
- Start to type "Logiciels" for example (if you have /usr/share/applications/org.gnome.Software.desktop)
- Application not found, but found under "Software"

**Expected behavior**
Show applications as "Logiciels" and find it when typing.

**Screenshots**

**Desktop**
- Arch
- Hyprland

**Additional context**
  󱞪 echo $LANG                                            
fr_FR.UTF-8

Looks linked to the scanning logics for .desktop which keep the last name found.

**Comment by abenz1267** [comment]
thanks for the hint. fixed in git/next release.

**Comment by androw** [comment]
Thanks!
