### ISSUE TITLE
Build 0.11.0  broke basic keyboard navigation

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#193]
**Describe the bug**
After invoking walker if I use arrow down to scroll down the list with the keyboard I'm getting inconsistent behavior.
- Sometimes the first arrow_down is ignored
- Sometimes it jumps a bunch of entries and go way down the list

**Version**
0.11.0

**To Reproduce**
Run walker, press arrow down.  
If all looks good, close walker and  try again at least 3 times.

**Expected behavior**
Should always go down one entry.

**Screenshots**

**Desktop**

- OS Arch
- DE Niri

**Additional context**
Downgraded to 0.10.22  and it fixed the issue.

**Comment by quadbyte** [comment]
Looking at the commits between 0.10.22 and 0.11 I see the refactoring with user definable keys.

I have not yet updated my config, so I have no keys {}  section in my config but was expecting it to work with default.

Attached my config to help.

[config.json](https://github.com/user-attachments/files/18222266/config.json)

**Comment by abenz1267** [comment]
It does work with default, the "problem" is that by default next/prev entry is `ctrl j/k`. You simply need to bind them to `down`/`up`.

The current behaviour is wonky, because that's the default GTK up/down behaviour, so actively binding next/prev to what you prefer is the way.

**Comment by abenz1267** [comment]
I should probably make up/down the default and not ctrl j/k.
