### ISSUE TITLE
Could you get it on dnf?

### ISSUE THREAD

**Issue by Heinrich-XIAO** [abenz1267/walker#196]
**Is your feature request related to a problem? Please describe.**
I want to install it on fedora without building it myself.

**Describe the solution you'd like**
Getting put on copr.

**Describe alternatives you've considered**

**Additional context**

**Have you checked the wiki?**
Yes?

**Comment by abenz1267** [comment]
https://copr.fedorainfracloud.org/coprs/errornointernet/walker/
