### ISSUE TITLE
Panic if ssh known_hosts file does not exist

### ISSUE THREAD

**Issue by tepri-gh** [abenz1267/walker#20]
Walker currently panics with the following error if the ssh known_hosts file does not exist:

`panic: open /home/tepri/.ssh/known_hosts: no such file or directory
 [recovered]
	panic: closure error: unexpected panic caught: open /home/tepri/.ssh/known_hosts: no such file or directory`
	
I store my file in a different location (~/.config/ssh/known_hosts), some users may not use ssh at all.

**Comment by abenz1267** [comment]
fixed by e5b5806.
