### ISSUE TITLE
Request for interactive performance improvement

### ISSUE THREAD

**Issue by redactedontop** [abenz1267/walker#201]
Hello.

I'm wondering if you'd let me do an interactive meeting/chat about potential performance improvements (in discord, telegram or something similar).

Thanks,
Alex <3

**Comment by abenz1267** [comment]
Why can't you just... suggest something in written form? :joy:

**Comment by redactedontop** [comment]
You're right, it's just it'd be instant feedback (better for my silly ADHD brain)

**Comment by redactedontop** [comment]
Plus idfk much go (rust ftw imo) so it'd help with syntax or other stuff I don't know.

**Comment by abenz1267** [comment]
But what's your concrete suggestion....

**Comment by redactedontop** [comment]
Not one concrete suggestion, just a full performance-based rewrite.

**Comment by abenz1267** [comment]
Sounds like a stupid thing to do? If there's a concrete performance bottleneck, one can fix it. This requires benchmarks.

Not even sure what "performance-based rewrite" even means. If there's a concrete problem, feel free to open a PR with a fix.
