### ISSUE TITLE
Walker does not recognize config and CSS file

### ISSUE THREAD

**Issue by Heus-Sueh** [abenz1267/walker#203]
**Describe the bug**
walker does not recognize config and CSS file

```
> ./launch_walker.sh 
layout file for theme '/home/heus/.config/walker/themes/modern/theme.css' not found
```

**Version**
0.11.4

**Minimal Config**
the same as default, just in a different folder to modify gradually

**To Reproduce**
try running walker with config and style modified through a script

```bash
#!/usr/bin/env bash

themes_dir="$HOME/.config/walker/themes"
theme="$themes_dir/modern"

if [[ -d "$theme" ]]; then
  if [[ -f "$theme/config.json" && -f "$theme/theme.css" ]]; then
    walker -c "$theme/config.json" -s "$theme/theme.css"
  else
    echo "Error: Theme files not found '$theme'." >&2
    exit 1
  fi
else
  echo "Error: '$theme' folder not found." >&2
  exit 1
fi
```

**Expected behavior**
Work like rofi

**Screenshots**
![image](https://github.com/user-attachments/assets/5b1cb536-4dbc-4108-ab88-ecfe63ddb649)

**Desktop**

- OS: Fedora Atomic
- DE: Hyprland

**Additional context**

**Comment by abenz1267** [comment]
This is wrong usage of the themeing. A theme always consists of 2 files: the style css and a layout file (json/toml/yaml). So you need `modern/theme.css` and `modern/theme.json`.

`walker -s theme` would then correctly work.

**Comment by abenz1267** [comment]
I'll actually modify the themeing slightly so the default css/layout will be used if not found.

**Comment by abenz1267** [comment]
So with the new version a single `modern/theme.css` without a layout file is fine, `walker -s modern/theme` would still be correct.

**Comment by abenz1267** [comment]
what version are you on....

**Comment by abenz1267** [comment]
the command to run walker with your theme is `walker -s modern/theme`

**Comment by abenz1267** [comment]
also: `-c` is for the whole walker config, not a theme layout.

**Comment by Heus-Sueh** [comment]
version: 0.11.4

![image](https://github.com/user-attachments/assets/f672e768-f708-4a4d-bea7-a824c33871ca)

**Comment by abenz1267** [comment]
update maybe.

**Comment by Heus-Sueh** [comment]
I will wait for the update to arrive on my distro, if the problem persists I will report it again, thanks for the help.

**Comment by abenz1267** [comment]
Ah, i thought you are on something more bleeding edge. You can always built yourself to test...

What distro are you on?

**Comment by Heus-Sueh** [comment]
> Ah, i thought you are on something more bleeding edge. You can always built yourself to test...
> 
> What distro are you on?

I'm on Fedora, using a third-party repo. I'll test it on a Distrobox container with Arch to see if it resolves.

**Comment by Heus-Sueh** [comment]
Did not resolve the issue by updating to the latest version (0.11.9), `walker` does not start with the defined theme

There are only things related to GPU in the log
[logs](https://privatebin.net/?06f7475a1530cb81#Dsm6hVcdJyc9FgMHd3gXcTTXVGmzev6Ja5MHHtKbELCP)

![image](https://github.com/user-attachments/assets/fdff69df-bf55-4230-b8e5-867c45266fae)
It is starting in the default theme

**Comment by abenz1267** [comment]
Are you trolling?

`walker -s ~/.config/walker/themes/modern/theme`

I told you 3 times now that the command would be `walker -s modern/theme`.

**Comment by Heus-Sueh** [comment]
> Are you trolling?
> 
> `walker -s ~/.config/walker/themes/modern/theme`
> 
> I told you 3 times now that the command would be `walker -s modern/theme`.

Now I understand, the "-s" already includes the themes directory by default, I was thinking that you need to pass the entire path, sorry for bothering you, I just found it counterintuitive, since in rofi and waybar both need the entire path
