### ISSUE TITLE
How to disable recent used application

### ISSUE THREAD

**Issue by syorito-hatsuki** [abenz1267/walker#204]
I can't find any community link, so I'm just asking here. 
![image](https://github.com/user-attachments/assets/05423c7c-823b-4765-bea6-043abea0e6b2)

**Comment by abenz1267** [comment]
You want to disable the history?

**Comment by syorito-hatsuki** [comment]
> You want to disable the history?

Not sure what is it, but it's like keeping 22 apps above, and only after that is it listed in a-z sorted list of apps. 
I just tried disable history, but don't seems to change anything (I restarted my Hyprland session for test it)
```json
    "applications": {
      "actions": {
        "enabled": false,
        "hide_category": false,
        "hide_without_query": true
      },
      "history": false, // by add this
      "context_aware": true,
      "hide_actions_with_empty_query": true,
      "name": "applications",
      "placeholder": "Applications",
      "prioritize_new": false,
      "refresh": true,
      "show_generic": true,
      "show_icon_when_single": true,
      "show_sub_when_single": true,
      "weight": 10
    },
```

**Comment by abenz1267** [comment]
Yeah, that was supposed to do the trick. It didn't fixed it. Will create a release shortly.

**Comment by syorito-hatsuki** [comment]
Let me re-open that)
Now issue is different, on first launch alright, but after search (and click to open program) sort breaking and I even don't understand with direction
![image](https://github.com/user-attachments/assets/070dd62e-a1e8-4a73-ac4b-d2cbd3e95516)

**Comment by syorito-hatsuki** [comment]
It's look like it keep sort that was after last search, or something in that direction

**Comment by abenz1267** [comment]
Should be fixed.

**Comment by syorito-hatsuki** [comment]
Yep, looks fine now :)
