### ISSUE TITLE
String escaping

### ISSUE THREAD

**Issue by Heinrich-XIAO** [abenz1267/walker#205]
**Describe the bug**
There is a warning about invalid markup like this when using non-escaped characters.
```
WARN Failed to set text 'OpenJDK 1.8.0 for x86_64 Monitoring & Management Console (1.8.0.432.b06-3.fc40.x86_64)' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp; priority=4 code_file=../gtk/gtklabel.c code_line=3764 code_func=gtk_label_set_markup_internal glib_domain=Gtk
```

**Version**
Walker version.0.11.7

**Minimal Config**
Provide a minimal config to reproduce the bug.
empty

**To Reproduce**
Steps to reproduce the behavior.
Install an application that has a name that includes and ampersand or any other character that requires escaping.

**Expected behavior**
The character should be escaped.

**Screenshots**

**Desktop**

- OS (Arch, Nix etc)
- DE (Plasma, Hyprland etc. )
Hyprland on fedora.

**Additional context**

**Comment by abenz1267** [comment]
That's actually rather tricky to solve non-stupid.

1.  I can't just html-escape the strings => this would interfere with fuzzy matching as `&` now becomes `&amp;` => matches on `amp` => need to avoid
2. I can't html-escape before printing out => the markup for matched characters is html as well

Dunno, maybe i'm missing something.

I "fixed" it by manually escaping only `&` now.
