### ISSUE TITLE
Walker won't run apps if runAsService = true;

### ISSUE THREAD

**Issue by Star-veil** [abenz1267/walker#27]
I'm on nixOS, I installed walker using the homemanager module;
I have three different scenarios:
- Launch walker normally, everything works as expected;
- Launch walker as service `walker --gapplication-service`, same as above, works fine and speeds up following launches
- Launch walker as service `programs.walker.runAsService = true;`, walker manages to open just fine, but when trying to launch something it returns `terminal is not set` and doesn't do anything, I am able to continue scrolling through the entries without the possibility to run it. Killing the service and running it again with `walker --gapplication-service` works fine.

**Comment by abenz1267** [comment]
1. what terminal are you using?
2. what command are you trying to run? regular desktop app or a terminal cmd?

**Comment by Star-veil** [comment]
1. kitty
2. both

**Comment by abenz1267** [comment]
Kitty should be recognized natively, if it's in your $PATH. From the past experience Nix users do weird stuff with their config :P. Might be a symlink issue?

Try setting the terminal in the config explicitly.

```json
{
"terminal": "kitty"
}
```

**Comment by Star-veil** [comment]
It actually tries to launch them now, but now it returns:
`exec: "vesktop": executable file not found in $PATH`
`exec: "lutris": executable file not found in $PATH`
etc..

> That might not help, if your $PATH is not set correctly before launching Walker.
I'm assuming it's this then, no idea what I could have that messes with this

**Comment by schromp** [comment]
Environment variables, such as path, are different when run as a systemd service.
I didnt have time to figure out a solution yet though

**Comment by abenz1267** [comment]
Ok, i'll close this here then for now, since it's not related to Walker.
