### ISSUE TITLE
Walker doesn't look like it should

### ISSUE THREAD

**Issue by DJXJD** [abenz1267/walker#33]
Walker looks pretty messed up for me, as can be seen in these screenshots:
![20240512_19h37m07s_grim](https://github.com/abenz1267/walker/assets/66258246/a6ac9515-9710-473f-a4f3-3d55a53ff11c)
![20240512_19h37m26s_grim](https://github.com/abenz1267/walker/assets/66258246/52ba052d-9351-41d4-8f70-e2ea1b2d73ef)

For reference, in order to get walker installed, I had to install `gtk4-layer-shell` like this:
```
paru -S --asdeps --mflags '--nocheck' gtk4-layer-shell
```

**Comment by abenz1267** [comment]
style to your liking in `~/.config/walker/style.css`. 

Default style: https://github.com/abenz1267/walker/blob/master/ui/themes/style.default.css

**Comment by DJXJD** [comment]
According to the following screenshot, shouldn't the default style look different than what I showed above? My screenshots above are immediately after installing, and I just compared the default style you linked with what I have applied, and they are identical.

![20240513_01h12m53s_grim](https://github.com/abenz1267/walker/assets/66258246/7f8c67ce-988e-45a9-a182-18a123fdc90e)

**Comment by DJXJD** [comment]
Sorry if I didn't make it clear that I was using the default style 😅

**Comment by abenz1267** [comment]
The screenshot on the readme is sliiightly outdated, but yours looks broken anyways. I can't really tell you what exactly is broken, since this depends on your systems theme.

This is what it looks for me if i set my system theme to adwaita-dark:

![2024-05-13T08:33:32,761711441+02:00](https://github.com/abenz1267/walker/assets/7055955/aa35899b-e6f6-4d54-956d-18aa4cd00a4e)

**Comment by PsyNyde** [comment]
hello I'm also currently facing similar issue where I configured walker to be horizontal but it's still taking the same width as vertical one for some reason? i tried also adding width: 1366px; to classes that seem to effect width but to no avail at the end

**Comment by abenz1267** [comment]
I can't help you, if you don't provide your config.
