### ISSUE TITLE
No Keyboard Input

### ISSUE THREAD

**Issue by cptn-cosmo** [abenz1267/walker#35]
I am using Niri (https://github.com/YaLTeR/niri) and would love to use walker with it. I can successfully launch it, but I can only interact with the walker window using the mouse. There is no keyboard input at all in the walker window. If i run walker from the terminal the inputs just go behind it into the terminal window instead.

**Comment by abenz1267** [comment]
I can't help you with this.

But since Walker run fine on Hyprland and Sway ( and other wayland compositors i can't remember the names from...) i guess it's an issue with niri. Sorry.
