### ISSUE TITLE
Add option to pass the input (%TERM%) via stdin

### ISSUE THREAD

**Issue by ItsDrike** [abenz1267/walker#41]
It'd be really neat if it was possible to pass the walker text input to given commad through stdin, instead of just having to use `%TERM%` there. This is because of the way shell escaping works, which makes it basically impossible to prevent injections. 

For example, currently, a module like this:
```json
    {
      "name": "test",
      "prefix": "!",
      "src": "echo '%TERM%'",
      "cmd": "notify-send 'test' '%RESULT%'"
    }
```

Does work, but only as long as the actual input doesn't contain `'`. After some messing around, it turns out there really is no good way at all to prevent injections/quote escaping like this in any way here. In fact, it gets even worse, if the `src` command is just: `echo %TERM%`, inputting `"hi"` will end up with just outputting `hi`, dropping the quotes entirely. This is a pretty big issue when the input needs some kind of special processing.

For a more real-world example, I wanted to make a custom web search module with duckduckgo, where I attempted doing this:
```json
    {
      "name": "DDG search",
      "prefix": "*",
      "src": "jq --arg input '%TERM%' -n -r '$input | @uri'",
      "cmd": "xdg-open https://duckduckgo.com/?t=h_&q=%RESULT%&ia=web"
    }
```

The `jq` here is for url-escaping. However, if my prompt contains `'`, it would just end up messing up the command.

One way to at least improve this, though not entirely fix it, would be to only perform the replacements after splitting the command into arguments, so that the entire input term is always a single argument. (Though for backwards compatibility, or some special cases, where people don't want that, it might be better to introduce something like `%SINGLETERM%`).

That said, the best way would definitely be to just allow passing the term via stdin. Perhaps if there's no `%TERM%` in `src`, this could be the default, or just add another bool param for the modules, like `pass_as_stdin`.

Ideally, there should probably also be an option to do this for the `cmd`.

**Comment by abenz1267** [comment]
will be passed via stdin now, if no %TERM% or %RESULT% is present.

Also for actual external scripts the input will no longer be implicitly passed as an arg, but also via stdin. can still be passed as an arg if explicitly defining %TERM%.

**Comment by abenz1267** [comment]
i've also added the ability to define various search engines for the websearch module.

```json
  "websearch": {
    "engines": ["google", "duckduckgo"]
  },
```

**Comment by abenz1267** [comment]
...can this be closed?

**Comment by ItsDrike** [comment]
I'm not sure, I am experiencing some issues when trying this with `jq -sRr '@uri'` command, everything seems to be working, up until there is a space or some other special character that needs url-encoding. I'm not sure why this is though.

There's also a bunch of errors in the output when running the walker command, related to some failed assertions.

Here's a video screen capture of this:

https://github.com/abenz1267/walker/assets/20902250/f220487b-dda2-498c-a017-413ad896c4c1


For reference, this is the external module definition:
```json
    {
      "name": "Test",
      "src": "jq -sRr '@uri'",
      "cmd": "notify-send 'test' '%RESULT%'",
      "switcher_exclusive": true
    }
```

And this is the text of that error message in the logs:
```
2024/07/08 03:30:10 ERROR gotk4_gbox_list_get_item: assertion 'index < objects_get_size(&self->items)' failed glib_old_log_api=1 priority=4
```

**Comment by ItsDrike** [comment]
Actually, this is probably not related to this issue, since testing with:
```
    {
      "name": "Test",
      "src": "cat",
      "cmd": "notify-send 'test' '%RESULT%'",
      "switcher_exclusive": true
    }
```
did work properly:

https://github.com/abenz1267/walker/assets/20902250/5e8653d9-d950-499f-a787-464e79142570

However the failed assertion and initialization errors are still present, even though things appear to be working.

**Comment by abenz1267** [comment]
The failed assertion errors are are caused by gotk4, see https://github.com/abenz1267/walker/issues/12.

**Comment by abenz1267** [comment]
What exactly do you mean? I put 

```json
    {
      "name": "Test",
      "prefix": "*",
      "src": "jq -sRr '@uri'",
      "cmd": "notify-send 'test' '%RESULT%'",
      "switcher_exclusive": false
    }
```

in my config and when i type in `*test` it works as expected.

**Comment by ItsDrike** [comment]
Try inputting `hello world` (with the space), or anything else that actually needs url encoding, like `#` symbol, etc. You can also see the issue in the video capture that I've recorded, notice how the moment I type in any such character, the item disappears.


https://github.com/abenz1267/walker/assets/20902250/d5eaea37-fb67-42c4-9960-d50a863b046e

I'm also not sure why, but the height of the launcher suddenly decreased, the same happened in the previous recording too, though in this one, it's to the point where even that first item almost doesn't fit.

**Comment by abenz1267** [comment]
That was a rather nasty bug:

1. You type in "#test"
2. "#test" gets url-escaped
3. the escaped result will be put in as the label
4. the fuzzy matching of `#test` vs the encoded string results in no match => empty list

I've fixed the issue by always un-escaping the label.
