### ISSUE TITLE
Expand environment variables

### ISSUE THREAD

**Issue by flytaly** [abenz1267/walker#44]
Currently, you have to provide the full path to your module. I propose replacing the environment variables in the path, so instead of
```json
      "src": "node /home/username/path/to/myscript.js"
```
you can specify
```json
      "src": "node $HOME/path/to/myscript.js"
```

[Here is the commit](https://github.com/flytaly/walker/commit/1cb834e14cb51f12d0869afd04b9b626cc1715ee), but I am not sure if there should be an additional option or if this is sufficient.

**Comment by abenz1267** [comment]
added.
