### ISSUE TITLE
Unexpected keybind behaviour when used with Hyprland.

### ISSUE THREAD

**Issue by leslie-kretai** [abenz1267/walker#45]
When `walker` is called from shell it runs just fine.

If set to be executed from a keybind in Hyprland such as below:

```
bind = SUPER, R, exec, walker
```
It will fail to launch and result in a lockfile being made. I was able to work around it by instead doing:

```
bind = SUPER, R, exec, alacritty -e zsh -c walker
```
However it will also display the terminal it was ran in instead of hiding it like Clipse does when I run a similar bind setup for that. I didn't see anything in the readme or the wiki on the recommended way to configure it for use in Hyprland, so I'm just curious if i've misconfigured this or if this is a bug.

**Comment by abenz1267** [comment]
I'm on Hyprland as well. Make sure that neither `/tmp/walker.lock` nor `/tmp/walker-service.lock` exist before launching.

I also just have `bind = ALT, RETURN, exec, walker` in my config. And for running the service i have `exec-once=walker --gapplication-service`.
