### ISSUE TITLE
Repeat rate breaks when drawing applications

### ISSUE THREAD

**Issue by donovanglover** [abenz1267/walker#5]
If there are one or more applications showing, then it becomes impossible to do things like hold backspace to clear the input

**Comment by abenz1267** [comment]
Can't replicate on my machine. Could you provide a small screen capture demonstrating the problem?

**Comment by abenz1267** [comment]
Feel free to check latest master and prob. adjust the search delay via config as you need.

Problem still present?

**Comment by donovanglover** [comment]
Using the following config fixes the issue for me. Thanks!

```json
{
  "search": {
    "delay": 300
  }
}
```
