### ISSUE TITLE
Execute different commands depending on key pressed

### ISSUE THREAD

**Issue by omnigenous** [abenz1267/walker#50]
Real world example:

I have emoji list that I want to search and copy or open emojipedia.org for that emoji.

Solution:

Let the user define a `cmd` that will be executed if certain key is pressed, for example when `Enter` pressed execute `cmd_ENTER` if `Shift+Enter` is pressed execute `cmd_SHIFT_ENTER`. I'm not sure what more elegant implementation would be just throwing ideas.

**Comment by abenz1267** [comment]
You can define `cmd_alt`/`exec_alt` now. `alt+enter` to run it.
