### ISSUE TITLE
Expose placeholder settings to cli flags

### ISSUE THREAD

**Issue by omnigenous** [abenz1267/walker#52]
Now we have dmenu mode (#47) would be nice to be able to change placeholder of walker with cli flag. Currently the only option is to create separate config file and pass it to `--config` flag.

`-p | --placeholder`

Example:

```
echo "chocolate\nvanilla" | walker -d -p "Pick you favorite ice cream"
```

---

Is there any other settings that could be exposed to cli flags which would be useful in combination with dmenu mode?

**Comment by abenz1267** [comment]
`-p, --placeholder` has been added.
