### ISSUE TITLE
External module cmd pipe

### ISSUE THREAD

**Issue by omnigenous** [abenz1267/walker#53]
Doesn't work:

```json
{
  "name": "test",
  "prefix": "t",
  "src_once": "echo '1 hello\n2 world\n3 foo\n4 bar'",
  "src_once_refresh": false,
  "cmd": "cut -d ' ' -f 2 | wl-copy",
  "cmd_alt": "echo"
}
```

Works:

```sh
echo '1 hello\n2 world\n3 foo\n4 bar' | walker -d | cut -d ' ' -f 2 | wl-copy
```

I would've just used dmenu mode but I want to also use `cmd_alt` and there no equivalent with dmenu mode afaik (https://github.com/abenz1267/walker/issues/47#issuecomment-2237680058)

**Comment by abenz1267** [comment]
Yeah, `cmd` is not a shell-interpreter. So that won't work. `cmd` is really just a cmd, piping in there doesn't work. It's not a shell.

What you could do is: 

```json
    {
      "name": "test",
      "prefix": "t",
      "src_once": "echo '1 hello\n2 world\n3 foo\n4 bar'",
      "src_once_refresh": false,
      "cmd": "~/test.sh",
      "cmd_alt": "echo"
    }
```

where content of "test.sh" is:

```bash
#!/bin/bash
cut -d ' ' -f 2 | wl-copy
```

Although i'm thinking about something.... let me cook.

**Comment by abenz1267** [comment]
Ok.... soooooo:

One approach would be what i wrote above, another one i just released:

`cmd_to_script` and `cmd_alt_to_script`: this will take the content of `cmd`/`cmd_alt` and put it into a bash script in `/tmp`. This script will be executed.

This way you can write whatever shell/bash commands you want.

**Comment by omnigenous** [comment]
I will try `cmd_to_script` but I think first approach you recommended is better for me since I already run into `"` escaping hell with longer one-liners and json.

**Comment by omnigenous** [comment]
walker 0.0.99-1 aur

```
echo '1 hello\n2 world\n3 foo\n4 bar' | walker -d | cut -d ' ' -f 2 | wl-copy
```
returns
```
panic: runtime error: index out of range [-1]

goroutine 36 [running]:
github.com/abenz1267/walker/modules.Dmenu.Entries({{0xc000034f80?, 0x0?, 0x0?}, 0x0?}, {0x0?, 0x0?}, {0x0?, 0x0?})
	/home/user/.cache/yay/walker/src/walker-0.0.99/modules/dmenu.go:20 +0x25f
github.com/abenz1267/walker/ui.processAsync.func5({0xce66e0?, 0xc0001da190?}, 0xc000298460?, {0x0, 0x0}, {0xce7fb0?, 0xc000216a60?})
	/home/user/.cache/yay/walker/src/walker-0.0.99/ui/interactions.go:744 +0xbf
created by github.com/abenz1267/walker/ui.processAsync in goroutine 8
	/home/user/.cache/yay/walker/src/walker-0.0.99/ui/interactions.go:741 +0x765
```

I assume it was caused by one of today's commits.

**Comment by abenz1267** [comment]
Argh... i see. Will fix.

**Comment by abenz1267** [comment]
should be fixed.

**Comment by omnigenous** [comment]
```
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/abenz1267/walker/archive/v0.0.100/walker-0.0.100.tar.gz
```

`https://github.com/abenz1267/walker/archive/v0.0.99/walker-0.0.99.tar.gz` works, something with github? I guess we should wait a bit.

**Comment by abenz1267** [comment]
Dunno why the url is broken... but i fixed the aur pkg. should work now.

**Comment by omnigenous** [comment]
> Ok.... soooooo:
> 
> One approach would be what i wrote above, another one i just released:
> 
> `cmd_to_script` and `cmd_alt_to_script`: this will take the content of `cmd`/`cmd_alt` and put it into a bash script in `/tmp`. This script will be executed.
> 
> This way you can write whatever shell/bash commands you want.

Can this also be done for `src` and `src_once`? Then I can have everything in walker config file.

**Comment by abenz1267** [comment]
i'd add it...

**Comment by abenz1267** [comment]
Ok, i've completely changed the way commands will be executed. Now every command should be executed as expected. So `cat | wl-copy` will just work. Applies to src and src_once as well.

**Comment by abenz1267** [comment]
can this be closed?

**Comment by omnigenous** [comment]
> can this be closed?

Hold on, `cmd_alt` doesn't work. I will wait for next walker version since there some new commits and see if it works there.

**Comment by abenz1267** [comment]
Ah.. will look into it. Just released a version.... you'll most likely need to redo your config.

**Comment by omnigenous** [comment]
Okay, updated. Now when pressing `alt+enter` walker executes `cmd` instead `cmd_alt`.

---

Also window renders wrong.

1. With my custom symbols/emoji list height is at it smallest value
2. Default `walker` without flags also got some sort of "hat" :D

1: ![1](https://github.com/user-attachments/assets/b77d2a18-41f3-48a9-b0c3-4f09eaeba5f2)
2: ![2](https://github.com/user-attachments/assets/293736f6-c979-4ae9-b449-b1866d2d6926)

**Comment by abenz1267** [comment]
1. i'd need your config for this to debug
2. that's expected, the default CSS also changed. the windows itself needs a transparent background.
3. will add

**Comment by abenz1267** [comment]
- alt+enter should be fixed now
- `placeholder` option to builtins/plugins added

**Comment by omnigenous** [comment]
> 1. i'd need your config for this to debug + your expected behaviour

Just copied default config.json and style.css. Run `walker -m apps` (any module would do), see:


![2024-07-21_04-10-30](https://github.com/user-attachments/assets/e3ce1989-3185-4619-8dd5-56fd32852e09)

Changing `list.height` doesn't seem to do anything

---

Realized a thing while I wrote above. `-m` or `--modules` flags doesn't actually do anything *unless* module is an external one aka plugin

**Comment by abenz1267** [comment]
1. list height: fixed
2. not sure what you mean.. works fine here. `apps` is not a module, `applications` is the name.

**Comment by omnigenous** [comment]
So is `walker -m clipboard` also wrong, because I get same result as in last screenshot with that? We need a list of built-in plugins in `--help` :D

**Comment by abenz1267** [comment]
No, `-m clipboard` works, but the clipboard in general only works, if Walker is running as a service, because the module depends on running as a service.

**Comment by omnigenous** [comment]
walker 0.1.3-git

Everything works as expected. Thank you for you work @abenz1267 <3

Gonna play with walker's css now :D
