### ISSUE TITLE
--keepsort but for plugins

### ISSUE THREAD

**Issue by omnigenous** [abenz1267/walker#61]
```
{
  "name": "test",
  "prefix": "t",
  "src_once": "echo \"c\nb\na\"",
  "cmd": "wl-copy"
}
```

^ Will be sorted alphabetically

Can we have `keep_sort`: `boolean` for plugins?

**Comment by abenz1267** [comment]
Yeah, will add. This will only work, if only a single module is being processed.

**Comment by abenz1267** [comment]
added.
