### ISSUE TITLE
SSH module wont parse SSH config

### ISSUE THREAD

**Issue by amnesiacsardine** [abenz1267/walker#62]
Starting v.0.1.6 ssh config should be parsed but in my case it is not. Launching walker from the terminal using `walker -m ssh` does not return any error message.

Only entries from known hosts appear in walker.

Here is my `~/.config/ssh`

```
host server
HostName 192.168.10.12
Port 22
User username
identityFile ~/.ssh/id_ed25519_sk_key1
IdentityFile ~/.ssh/id_ed25519_sk_key2
RemoteForward /run/user/1000/gnupg/S.gpg-agent /run/user/1000/gnupg/S.gpg-agent.extra 
RemoteForward /run/user/1000/gnupg/S.gpg-agent.ssh /run/user/1000/gnupg/S.gpg-agent.ssh
```
I have multiple hosts but there are all configured the same. Simply different `HostName` , `Port`, and  `User`.

**Comment by abenz1267** [comment]
i'm not too familiar with the details here, but does it matter if `host` is `Host` vs `host`?

Walker looks for `Host`. If it doesnt matter if it's `host` or `Host` i can simply check for both variants.

**Comment by amnesiacsardine** [comment]
Changing `host` to `Host` in my config made walker detect it. As far as I know `Host` and `host` are 2 valid spelling for the exact same thing. I guess it would make sense to make walker look for both.

More of a suggestion than an issue at this point so feel free to close the issue either way.

**Comment by abenz1267** [comment]
No, i will implement it. I just wasn't sure, because you have

```
identityFile ~/.ssh/id_ed25519_sk_key1
IdentityFile ~/.ssh/id_ed25519_sk_key2
```

and i thought there's maybe some case-sensitive stuff going on, like "if this is lower case => ignore it"

**Comment by abenz1267** [comment]
it's done. will be in the next release.
