### ISSUE TITLE
Allow prefixes with multiple characters

### ISSUE THREAD

**Issue by flytaly** [abenz1267/walker#63]
Currently, prefixes can only consist of one character, which is very restrictive. And you cannot even use letters as prefixes, as every letter could be a prefix for some other application.

Also, this kind of prefixes  should activate the plugin only if there is a space after the prefix, similar to how Alfred, popular Mac OS launcher, works.  This way you won't miss other entries and can have unlimited plugins.

<img width="500" src="https://github.com/user-attachments/assets/f7472c43-50dd-4fc3-b7ed-37cea12024c9">

<img width="500" src="https://github.com/user-attachments/assets/ef32b54a-55e8-49a2-b7d2-11fd00c00207">

If the prefix is 1 character long, the behavior should probably remain the same, so you can still use things like "=3+3", "/app" e.t.c.

**Comment by abenz1267** [comment]
Ah yes, this seems much better and flexible. Added in 0.3.0.
