### ISSUE TITLE
Weird behavior in dmenu mode

### ISSUE THREAD

**Issue by omnigenous** [abenz1267/walker#65]
```sh
echo "c\nb\na" | walker -d
```

- `e`, `d`, `u`, `n` or `m` matches everything
- Pressing letter that matches history `+` `tab` completes from history, not useful in dmenu mode (ex: `h` + `tab` = `hello`)
- Pressing `arrow up` puts `f` in search box doesn't happen with `shift` + `tab`

**Comment by abenz1267** [comment]
1. fixed (caused by matching other stuff Walker normally matches against, f.e. the sub.. in this case "dmenu"
2. fixed: disabled typeahead for dmenu-mode
3. fixed: disabled up-history in dmenu-mode
