### ISSUE TITLE
Allow user to cycle through list

### ISSUE THREAD

**Issue by omnigenous** [abenz1267/walker#66]
```sh
echo "c\nb\na" | walker -d
```

1. Select last item
2. Press `Arrow Down` or `Tab`
3. Nothing happens

Would be great to have an option to cycle through list so on step `3` selection goes back to item 1. Not necessary just for dmenu mode could be great when used with single module defined from plugin.

**Comment by abenz1267** [comment]
added `cycle` boolean to list config.
