### ISSUE TITLE
nix: binary cache not working?

### ISSUE THREAD

**Issue by Ciflire** [abenz1267/walker#70]
I setup the binary cache as specified in the wiki but still have to rebuild from source everytime

**Comment by abenz1267** [comment]
sorry, I can't help you, since I don't use nix. I leave this issue open in case someone else has a solution.

**Comment by Ciflire** [comment]
Hi, i managed to set up the binary cache
I don't know how to troubleshot this for the repo tbh without any rights on it

**Comment by Ciflire** [comment]
I can see from the github actions that this is pushed to cachix, so nothing's wrong here,
could it be that the cachix is private?

**Comment by abenz1267** [comment]
![image](https://github.com/user-attachments/assets/13a2ec52-1396-41b7-b574-bb888b7cb71d)

**Comment by Ciflire** [comment]
i don't understand really

**Comment by Ciflire** [comment]
```
   nix.settings = {
-    substituters = [ "https://walker.cachix.org" ];
-    trusted-public-keys = [ "walker.cachix.org-1:fG8q+uAaMqhsMxWjwvk0IMb4mFPFLqHjuvfwQxE4oJM=" ];
+    substituters = [
+      "https://walker.cachix.org"
+      "https://hyprland.cachix.org"
+    ];
+    trusted-public-keys = [
+      "walker.cachix.org-1:fG8q+uAaMqhsMxWjwvk0IMb4mFPFLqHjuvfwQxE4oJM="
+      "hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc="
+    ];
   };
```
well believe it or not here is the diff of my file between the "does compile an takes 10 minutes" to "now it works"

**Comment by abenz1267** [comment]
... basically just adding hyprland cache?! I'm confused.

**Comment by Ciflire** [comment]
i added hyprland cache but that's not supposed to intefere
there might have a difference in sha or smth i don't know
