### ISSUE TITLE
nix: walker-0.4.1-git-go-modules getting a hash mismatch

### ISSUE THREAD

**Issue by AlxTray** [abenz1267/walker#79]
After attempting to update my flake, I am getting a hash mismatch in my fixed-output derivation from the dropIconThemeCache. Don't know if this is just me, but currently is not updating on Nix.

**Comment by abenz1267** [comment]
can you try again? updated the hash. (its building from source, right?)

**Comment by AlxTray** [comment]
Yep, it's updating now, thanks. And yeah, from source.
