### ISSUE TITLE
[Feature] Ignore initial cursor positon

### ISSUE THREAD

**Issue by Visual-Dawg** [abenz1267/walker#83]
## What

disable initial mouse selection via config

## Why

I oftentimes end up having my mouse/cursor in the center of the screen and when opening walker it hovers already over some search result. 

But I just quickly press `arrow-down` to select the first item and then enter.

However, as there was already a result selected it just goes below that one and then opens the wrong one.

Being able to disable the first hover would make it a lot smoother

**Comment by abenz1267** [comment]
you can set `"ignore_mouse": true`

**Comment by abenz1267** [comment]
I've added `"single_click": true` (default) to the `list` config, which you can set to `false`. This will disable the hover-selection completely without having to use `ignore_mouse`.

**Comment by Visual-Dawg** [comment]
Thank you a lot!
Sorry for the late reply and thank you again for your great work 

29 Jul 2024, 08:12 by ***@***.***:
