### ISSUE TITLE
Spinner doesn't appear

### ISSUE THREAD

**Issue by Noah765** [abenz1267/walker#84]
Reproduction steps:
1. Modify `config.json` to include `"search": { "spinner": true }`.
2. Modify `style.css` to make the spinner visible by default: `#spinner { opacity: 1; }`.
3. Launch walker

I'm using the latest version of walker (bcd6be6) and also get this error, whether I enable or disable the spinner:
```
ERROR gdk_pixbuf_loader_set_size: assertion 'width >= 0 && height >= 0' failed glib_old_log_api=1 priority=4 glib_domain=GdkPixbuf
ERROR gdk_pixbuf_loader_set_size: assertion 'width >= 0 && height >= 0' failed glib_old_log_api=1 priority=4 glib_domain=GdkPixbuf
ERROR gdk_pixbuf_loader_set_size: assertion 'width >= 0 && height >= 0' failed glib_old_log_api=1 priority=4 glib_domain=GdkPixbuf
ERROR gdk_pixbuf_loader_set_size: assertion 'width >= 0 && height >= 0' failed glib_old_log_api=1 priority=4 glib_domain=GdkPixbuf
```

Using the GTK inspector, I noticed that the GtkSpinner object doesn't even exist.

**Comment by abenz1267** [comment]
fixed.
