### ISSUE TITLE
Starting Walker with `-m` disables the `sub` text

### ISSUE THREAD

**Issue by Noah765** [abenz1267/walker#87]
Reproduction steps:
1. Use the default config
2. Run `walker -m applications`

**Comment by abenz1267** [comment]
Yes. That is expected behaviour. You can set "show_sub_single_module" in your list config.

But this will be revised with the upcoming big UI customization changes. As this setting should be configurable per module and not globally.

**Comment by Noah765** [comment]
Sorry, I seem to have somehow overlooked this option. Keep up the great work, your response times to the issues I have opened are unparalleled.
