### ISSUE TITLE
[Request] Module calculator, metric and currency convertion

### ISSUE THREAD

**Issue by vuongtuha** [abenz1267/walker#91]
Idk how Krunner perform this acytion, but I would suggest to use qalculate 
metric system from this website https://www.metric-conversions.org/converter.htm
idk how to convert currency (relative of time)

**Comment by abenz1267** [comment]
You can just create a simple plugin yourself. There's even an example using Rink on the wiki page.

**Comment by abenz1267** [comment]
![image](https://github.com/user-attachments/assets/14f5b54a-275c-4943-8cc3-b3cd3c2deda1)

**Comment by abenz1267** [comment]
i've added it. but you got to have `libqalculate` installed. It does stuff like currency conversion etc. by itself.
